### ISSUE TITLE
Problems in WPF apps that use Fody Costura for merging assemblies into main executable

### ISSUE THREAD

**Issue by aleksander-oven** [MahApps/MahApps.Metro.IconPacks#107]
Adding any of the icon packs NuGets to a WPF application that uses Fody Costura results in the following:

1. XAML editor underlines all resources (even the ones from local assembly) with error saying "An item with the same key has already been added".
2. Code compiles fine, but an exception is thrown on app startup, with the same message as above.

Adding the MahApps.Metro.IconPacks NuGet to Costura's ExcludeAssemblies has no effect. The error goes away only when either Costura is disabled or IconPacks NuGet is removed from project.

Is there a way to fix this problem and be able to use the icon packs together with Fody Costura?

**Comment by punker76** [comment]
@aleksander-oven Which version of IconPacks are you using? By the way, the IconPacks browser uses Fody Costura and has no problems with this. Latest version of Fody Costura on the dev branch is v3.1.4

https://github.com/MahApps/MahApps.Metro.IconPacks/blob/4c1fde8d3c5a438275bf9d92e2b177cd83e79d14/src/paket.lock#L5-L6

**Comment by aleksander-oven** [comment]
I'm on Fody Costura v3.1.4. As for the MahApps.Metro.IconPacks, its v2.3.0.

I'm actually glad to hear about the browser! It means the problem must be related to something else. What bothers me is that I can't understand which resource key the error is talking about. In XAML editor, even the references to commands are underlined as errors. Basically every named resource that is defined in the main project.

**Comment by aleksander-oven** [comment]
After trying the Costura + MahApps.Metro.IconPacks in a brand new WPF project, I can conclude that it indeed works without any problems. I'll now try slowly re-adding everything step by step and see where the problem reappears. I apologize for raising the issue here.

**Comment by punker76** [comment]
@aleksander-oven you're welcome!
