### ISSUE TITLE
iconpath alignment issue

### ISSUE THREAD

**Issue by touseefbsb** [MahApps/MahApps.Metro.IconPacks#108]
I noticed that after using MaterialDesign IconPath in my NavigationViewItem the icons seem to be drifting a little towards right as you can see in this image. This does not happen if using default symbolIcon control.

![image](https://user-images.githubusercontent.com/11542189/47837926-88ecf700-ddcf-11e8-8c4e-dd6e13d36a8b.png)

**Comment by touseefbsb** [comment]
any idea why this is happening @punker76  ?

**Comment by punker76** [comment]
@touseefbsb Just tried it with the NavigationView and can not see this issue...

![image](https://user-images.githubusercontent.com/658431/49545775-da146d00-f8de-11e8-9e41-0cb13f1a3c05.png)

**Comment by touseefbsb** [comment]
oh then its probably something wrong in my app, thanks for confirming.
