### ISSUE TITLE
IconPacks for Xamarin

### ISSUE THREAD

**Issue by Suplanus** [MahApps/MahApps.Metro.IconPacks#115]
Existing libraries are not that good 😘

**Comment by tenninebt** [comment]
Has anyone looked into this? Any one has an idea what makes the package incompatible?

**Comment by punker76** [comment]
=> #340

**Comment by trydalch** [comment]
There are apps that are built on .net for iOS and .net for Android (formerly Xamarin) that do not use Maui. 

This would be a nice addition (particularly for those using Uno Platform)
