### ISSUE TITLE
The tag 'Material' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/iconpacks'. 	

### ISSUE THREAD

**Issue by allenlili** [MahApps/MahApps.Metro.IconPacks#119]
In XAML,

```
<MenuItem Header="Save" Margin="5 0 0 0" Padding="0" Icon="{iconPacks:Material ContentSave, Height=12, Width=12}"/>
```

After building project, 'Error List' displays 'The tag 'Material' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/iconpacks'. 

How to avoid this? Thanks.

**Comment by punker76** [comment]
@allenlili Please, provide some more informations like

- VS version?
- IconPacks version?
- Which target (AnyCPU, x86, x64)?
- Targetframework?

Thx

**Comment by emptienater** [comment]
Make sure to install the [MahApps.Metro.IconPacks](https://github.com/MahApps/MahApps.Metro.IconPacks) for your project.

> 
> To install the IconPacks, run the following commands in the NuGet Package Manager Console or install it with the NuGet Package Manager extension.
> 
>     MahApps.Metro.IconPacks includes all Icons in one package on NuGet
> 
>     PM> Install-Package MahApps.Metro.IconPacks

**Comment by allenlili** [comment]
> In XAML,
> 
> ```
> <MenuItem Header="Save" Margin="5 0 0 0" Padding="0" Icon="{iconPacks:Material ContentSave, Height=12, Width=12}"/>
> ```
> After building project, 'Error List' displays 'The tag 'Material' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/iconpacks'.
> 
> How to avoid this? Thanks.

VS version 2015
IconPacks version: 2.3.0
target: x86
targetframework: .net4.5

**Comment by SAMUD** [comment]
I opened an old project from summer last year and get the same error.

`Der Name "PackIconMaterial" ist im Namespace "http://metro.mahapps.com/winfx/xaml/iconpacks" nicht vorhanden.`

I'm getting this with PackIconMaterial or whatever else for Icons I want to use.
IntelliSense is showing me the hints for the IconPacks, but as soon as I tap enter the code 
`<iconPacks:PackIconMaterial ......." />` gets underlined and shows this error.

VS-version is: 15.9.2 Community 2017
MahApps.Metro is 1.6.4
MahAps.Metro.IconPacks is 2.2.0
--> also tried to upgrade to current release 1.6.5 and 2.3.0

**Comment by punker76** [comment]
@allenlili @SAMUD Can you try to clean all bin and obj folders and build it again? Another tipp is to clean the Designer ShadowCache located in `C:\Users\<USER>\AppData\Local\Microsoft\VisualStudio\14.0\Designer\ShadowCache` (or whatever VS is installed)

**Comment by punker76** [comment]
@allenlili @SAMUD ping

**Comment by SAMUD** [comment]
@punker76 Sorry for not answering. I was busy.

I just had to reinstall my PC. So I'm starting of a clean install now. I cleaned all bin and obj folders, but didn't find the ShadowCache folder. 

Errors are still the same:
![image](https://user-images.githubusercontent.com/10502656/55378691-50864c00-551a-11e9-971f-7aa9eaba0f36.png)

I attached some parts of the code:
`<Controls:MetroWindow   x:Class="TiaImporter.MainWindow"
                        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
                        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
                        xmlns:Dialog="clr-namespace:MahApps.Metro.Controls.Dialogs;assembly=MahApps.Metro"
                        xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
                        xmlns:iconPacks="http://metro.mahapps.com/winfx/xaml/iconpacks"
                        mc:Ignorable="d"
                        
                        Title="TIA IMPORTER" Height="900" Width="1000"
                        MinHeight="800" MinWidth="700"
                        ResizeMode="CanResize"
                        Icon="icon_nJ8_icon.ico"
                        ShowIconOnTitleBar="True"

                        Dialog:DialogParticipation.Register="{Binding}">
    <Window.Resources>`


and here is one place with the error:
`<Controls:Tile Title="Open Project" 
                               Margin="3"
                               Visibility="{Binding OpennessFunctions.IsConnected, Mode=OneWay, UpdateSourceTrigger=PropertyChanged, Converter={StaticResource BoolToVis}}"
                               IsEnabled="{Binding OpennessFunctions.IsConnected, Mode=OneWay, UpdateSourceTrigger=PropertyChanged}"
                               Click="Button_ClickProjectOpen"
                               Controls:ControlsHelper.MouseOverBorderBrush="{DynamicResource BlackBrush}"
                               Background="OrangeRed"
                               HorizontalTitleAlignment="Right"
                               Style="{StaticResource LargeTileStyle}">
                            <iconPacks:PackIconMaterial Width="40"
                                              Height="40"
                                              Kind="EmailOpen" />
                        </Controls:Tile>`

**Comment by punker76** [comment]
@SAMUD Here is my try with exact the same conditions like MahApps.Metro v1.6.5 and IconPacks v2.2.0. I used VS 2015 and all works fine => https://github.com/punker76/WpfAppMahAppsIconPacks

**Comment by SAMUD** [comment]
Im running VS2017 community.

If you want I can send you my project, so you can see it directly there :)

**Comment by punker76** [comment]
@SAMUD The sample works also under VS 2017 and VS 2019.

>If you want I can send you my project, so you can see it directly there :)

:-D you can do this via Gitter private chat room

**Comment by SAMUD** [comment]
> @SAMUD The sample works also under VS 2017 and VS 2019.
> 
> > If you want I can send you my project, so you can see it directly there :)
> 
> :-D you can do this via Gitter private chat room

Ok. I sent you a message
