### ISSUE TITLE
How to create a new IconPack Object from SVG Path?

### ISSUE THREAD

**Issue by yasmanycruz79** [MahApps/MahApps.Metro.IconPacks#123]
I have a custom SVG Icon and i need to get a IconPack Object in Code, please help!!!

**Comment by punker76** [comment]
@yasmanycruz79 I created a repo which shows how to create such a custom icon pack:

https://github.com/punker76/WpfAppMahAppsIconPacks#how-to-create-a-new-iconpack-object-with-custom-svg-paths

**Comment by yasmanycruz79** [comment]
Awesome!!! thanks!! is great!!!

**Comment by amkuchta** [comment]
@punker76 any chance you are willing to share the script you use to automatically parse large numbers of SVGs?
