### ISSUE TITLE
Icons missing from the 3.0.0-alpha0146

### ISSUE THREAD

**Issue by alekdavis** [MahApps/MahApps.Metro.IconPacks#126]
I am using the IconPack Browser v1.5.0.0 (with IconPacks v2.3.0.4) and IconPacks v3.0.0-alpha0146 in my app, and quite a few icons that browser shows in v 2.3 are missing from the alpha. For example, AccountSettingsVariant, SecurityAccount, and more.

![IconPacks](https://user-images.githubusercontent.com/2113681/57961660-53b87a00-78c5-11e9-9b44-4e1f02378511.PNG)

![IconPacksBrowser](https://user-images.githubusercontent.com/2113681/57975125-96875a00-7978-11e9-95a6-3a561918ffed.PNG)

Environment:
 - IconPacks Version: v3.0.0-alpha0146
 - Visual Studio: 2017 Enterprise
 - .NET Framework: 4.6.1
 - Application type: WPF

Is this a known issue?

**Comment by punker76** [comment]
@alekdavis The v3.0 alpha uses new/updated icons, so the browser from v2.3 is not compatible. You can download the latest browser from the [azure pipeline](https://dev.azure.com/mahapps/MahApps.Metro.IconPacks/_build?definitionId=3)

![image](https://user-images.githubusercontent.com/658431/59337157-4cd42a00-8d00-11e9-9b8a-e95fd5621f57.png)

![image](https://user-images.githubusercontent.com/658431/59337160-4f368400-8d00-11e9-9e76-c74b3bcab271.png)

![image](https://user-images.githubusercontent.com/658431/59336889-b6a00400-8cff-11e9-9935-6b318835d4ab.png)
