### ISSUE TITLE
The method or operation is not implemented

### ISSUE THREAD

**Issue by romigrabarz** [MahApps/MahApps.Metro.IconPacks#127]
I create a simple window like that:
`new UserControl1();`
and have an exception:

> System.Windows.Markup.XamlParseException
>   HResult=0x80131501
>   Message=The method or operation is not implemented.
>   Source=PresentationFramework
>   StackTrace:
>    at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
>    at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
>    at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
>    at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
>    at Test.Views.UserControl1.InitializeComponent() in C:\VS\Test\Views\UserControl1.xaml:line 1
> 
> Inner Exception 1:
> NotImplementedException: The method or operation is not implemented.
>    at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlType(BamlType bamlType, Int16 typeId)
>    at System.Windows.Baml2006.Baml2006SchemaContext.GetXamlType(Int16 typeId)
>    at System.Windows.Baml2006.Baml2006SchemaContext.GetProperty(Int16 propertyId, XamlType parentType)
>    at System.Windows.Baml2006.Baml2006Reader.Process_PropertyWithConverter()
>    at System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
>    at System.Windows.Baml2006.Baml2006Reader.Process_BamlRecords()
>    at System.Windows.Baml2006.Baml2006Reader.Read()
>    at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
>    at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)

Exception is throw by InitializeComponent() method in UserControl1 constructor:
```
public partial class UserControl1 : Window
    {
        public UserControl1()
        {
            InitializeComponent(); //throw exception
        }
    }
```

My UserControl1.xaml code:
```
<Window x:Class="Test.Views.UserControl1"
                 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                 xmlns:icon="http://metro.mahapps.com/winfx/xaml/iconpacks">
    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro.IconPacks;component/Themes/IconPacks.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Window.Resources>

     <Grid>
        <icon:PackIconFontAwesome Kind="AddressBookRegular"/>
    </Grid>
</Window>
```

When I remove line starts with <icon..., then everything works fine. 
If I create xaml window programmaticaly, then works too without exception:
```
var assembly = System.Reflection.Assembly.Load("MahApps.Metro.IconPacks, Version=3.0.2.4, Culture=neutral, PublicKeyToken=null");
var icon = assembly.CreateInstance("MahApps.Metro.IconPacks.PackIconFontAwesome") as MahApps.Metro.IconPacks.PackIconFontAwesome;
icon.Kind = MahApps.Metro.IconPacks.PackIconFontAwesomeKind.AddressBookRegular;
var w = new UserControl1();
var stackPanel = new StackPanel { Orientation = System.Windows.Controls.Orientation.Vertical };
stackPanel.Children.Add(new System.Windows.Controls.Button { Content = icon, Height = 100 });
w.Content = stackPanel;
w.Show();
```
I have to load assemby MahApps.Metro.IconPacks although it's added by reference in my project.
How to solve this problem to use Mah Icons in my xaml designer?

**Desktop Environment:**
 - IconPacks Version: 2.3.0.4
 - ControlzEx Version: 3.0.2.4
 - Visual Studio Enterprise 2019 16.0.4
 - .NET Framework: 4.7.2

**Comment by punker76** [comment]
@romigrabarz Seems like you load a wrong version of IconPacks at this line:

```
var assembly = System.Reflection.Assembly.Load("MahApps.Metro.IconPacks, Version=3.0.2.4, Culture=neutral, PublicKeyToken=null");
```

The version should be v2.3.0.4. Additionally maybe you must load the ControlzEx too.

**Comment by romigrabarz** [comment]
Thanks for replay.
I fix assembly version, but problem still exists.
I try to load assembly from path but nothing happend:

```
 public UserControl1()
        {
            Assembly.LoadFrom("My path to ControlzEx.dll");
            Assembly.LoadFrom("My path to MahApps.Metro.IconPacks.dll");
            ResourceDictionary rd = new ResourceDictionary();
            rd.Source = new Uri(@"pack://application:,,,/MahApps.Metro.IconPacks;component/Themes/IconPacks.xaml");

            InitializeComponent();
        }
```

My dll's is another path than my exe, like this:
C:\Test\MyProgram.exe
D:\Dll\ControlzEx.dll
D:\Dll\MahApps.Metro.IconPacks.dll

When I copy those dlls to exe path, then everything works fine. But I have to seperate dlls to exe.
How to achive/solve this?

**Comment by punker76** [comment]
@romigrabarz I think what you need is embedding an assembly and reference it at the same time. Or you use some known libraries which does this for you in a magical way, like Costura Fody or ILMerge.

Here are some links to help you out:
- https://stackoverflow.com/a/9260325/920384
- https://www.codeproject.com/Articles/32828/Using-Reflection-to-load-unreferenced-assemblies-a

**Comment by romigrabarz** [comment]
Thanks!
I solved problem with use Costura Fody and merge missing assemblies into one dll like this (FodyWeavers.xml):
```
<?xml version="1.0" encoding="utf-8"?>
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
  <Costura>
    <IncludeAssemblies>
      MahApps.Metro.IconPacks
      ControlzEx
    </IncludeAssemblies>
  </Costura>
</Weavers>
```

Everything works without any exceptions!
