### ISSUE TITLE
.Net Core 3 XamlParseException: The method or operation is not implemented

### ISSUE THREAD

**Issue by Insire** [MahApps/MahApps.Metro.IconPacks#136]
**Describe the bug**
Using the MahApps.Metro.IconPacks.FontAwesome nuget package, i get a XamlParseException (The method or operation is not implemented) thrown in PresentationFramework.dll.

**To Reproduce**
1. clone [this](https://github.com/Insire/MahApps.Metro.IconPacks.IconLoadingProblem)
2. compile
3. run

**Expected behavior**
Program starts and icon is being loaded inside the button.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/11455827/60039147-5c675180-96b6-11e9-8c1b-a64d63f87a9e.png)

**Desktop Environment:**
 - IconPacks Version: 2.3.0
 - Visual Studio: 16.1.3 (Community )
 - .NET (core) Framework: 3.0.100.11568 (preview 5, x64)

Possible duplicate of #127

**Comment by Insire** [comment]
I can reproduce this on another PC running:
Visual Studio: 16.1.3 (Professional)
.NET Framework: 3.0.100.11223 (preview 4, x64)

**Comment by Insire** [comment]
Also, i just forked and cloned this repo and tried reproducing that with the PC i just mentioned and a new app and the problem does not occur. Weird.

**Comment by punker76** [comment]
@Insire You must use the latest alpha of IconPacks together with .Net Core 3 Preview 6. Version 2.3.0 is not for .Net Core 3.0
