### ISSUE TITLE
Can't compile UWP project referencing preview version of MahApps.Metro.IconPacks.Octicons

### ISSUE THREAD

**Issue by patriksvensson** [MahApps/MahApps.Metro.IconPacks#137]
**Describe the bug**

For some reason, I cannot build any UWP project that references version `3.0.0-alpha0176` of `MahApps.Metro.IconPacks.Octicons`. The project compiles if installing the previous version (`3.0.0-alpha0169`).

**To Reproduce**

* Create a new UWP project targeting minimum version `17736`
* Install version `3.0.0-alpha0176` of the `MahApps.Metro.IconPacks.Octicons` NuGet package
* Try to compile the project

**Expected behavior**

The project compiles without any errors.

**Workaround**

Install version `3.0.0-alpha0169` which works OK.

**Comment by patriksvensson** [comment]
@punker76 Still seeing this issue in both version `v3.0.0-alpha0179` of `MahApps.Metro.IconPacks` and `MahApps.Metro.IconPacks.Octicons`.

**Comment by patriksvensson** [comment]
@punker76 There seems to have been a regression introduced in version `v3.0.0-alpha0189` of the `MahApps.Metro.IconPacks.Octicons` package. Getting `Cannot find type Windows.UI.Xaml.Markup.MarkupExtension in module` when compiling the project.

Downgrading to version `v3.0.0-alpha0188` works as expected.

**Comment by punker76** [comment]
@patriksvensson Damn, the only change at this version was to change the .Net Core 3 SDK to Preview 7 and using a newer `MSBuild.Sdk.Extras`. I will try to go back to the prior version of `MSBuild.Sdk.Extras`.

https://github.com/MahApps/MahApps.Metro.IconPacks/commit/48befffa5cdf5809d1a469745f1f93bca536c9d5
