### ISSUE TITLE
Namespace Issue

### ISSUE THREAD

**Issue by Jacquers** [MahApps/MahApps.Metro.IconPacks#145]
I'm getting a weird one...

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'FontAwesomeExtension' exists in both 'MahApps.Metro.IconPacks.FontAwesome, Version=2.3.0.4, Culture=neutral, PublicKeyToken=null' and 'MahApps.Metro.IconPacks, Version=2.3.0.4, Culture=neutral, PublicKeyToken=null'	

`<controls:MetroWindow
    x:Class="VSC.SILS.Desktop.Views.MessageWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:controls="http://metro.mahapps.com/winfx/xaml/controls"
    xmlns:iconPacks="http://metro.mahapps.com/winfx/xaml/iconpacks"
    Title="MessageWindow" Icon="../Images/logo.ico"
    WindowTitleBrush="#222034" BorderBrush="#222034"
    WindowStartupLocation="CenterScreen"
    SizeToContent="WidthAndHeight">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>

        <StackPanel Orientation="Horizontal" Margin="15">
            <ContentControl VerticalAlignment="Center">
                <iconPacks:FontAwesome x:Name="img" Kind="ExclamationTriangleSolid" />
            </ContentControl>
            <Label Name="lblMessage" Content="Message will be shown here ... " />
        </StackPanel>

        <StackPanel Background="#F2F4F8" Orientation="Horizontal" HorizontalAlignment="Right" VerticalAlignment="Bottom" Grid.Row="1">
            <Button Name="btnOk" Content="OK" Width="75" Margin="3" />
            <Button Name="btnCancel" Content="Cancel" Width="75" Margin="3" />
        </StackPanel>
    </Grid>
</controls:MetroWindow>`

Any help appreciated :)

**Comment by punker76** [comment]
@Jacquers You don't need to add the `MahApps.Metro.IconPacks.FontAwesome` NuGet package if you already added the `MahApps.Metro.IconPacks` NuGet package.

**Comment by Jacquers** [comment]
Fixed, thanks!
