### ISSUE TITLE
some Material Database icons are not in the nugget package

### ISSUE THREAD

**Issue by raggnic** [MahApps/MahApps.Metro.IconPacks#148]
If i run the Iconpacks browser there are several icons for database (like edit, import and so on)
When I import the Nuget package, there are not all in the PackIconMaterial package

**Comment by timunie** [comment]
There are several different iconpacks available. Make sure you have the ones needed installed or all of them installed. Is the icon now available? 

Happy coding
Tim

**Comment by raggnic** [comment]
Thank you for answering :)
I've installed the whole MahApps.Metro.IconPacks Nuget.
I'm trying to display the Database icons from the Material 

```
 <Button x:Name="removeAssetButton" ToolTip="Remove selected Asset" Margin="10,0,0,0"   
                        Click="removeAssetButton_Click" 
                        IsEnabled="{Binding IsRemoveButtonEnabled}">

                <iconPacks:PackIconMaterial Width="32"
                                       Height="32"
                                       HorizontalAlignment="Center"
                                       VerticalAlignment="Center"
                                       Kind="DatabaseMinus" />
                </Button>
<Button x:Name="updateAssetButton" ToolTip="Edit selected Asset" Margin="10,0,0,0"   
                    
                        IsEnabled="{Binding IsRemoveButtonEnabled}">

                <iconPacks:PackIconMaterial Width="32"
                                       Height="32"
                                       HorizontalAlignment="Center"
                                       VerticalAlignment="Center"
                                       Kind="DatabaseEdit" />
                </Button>
```
DatabaseMinus is present but not DatabaseEdit, altough it is present in the IconPacks browser.
Maybe I'm doing something wrong?

**Comment by timunie** [comment]
I think I know what is going on. Some Icons were renamed. Try Intelligence to find the correct name.

**Comment by timunie** [comment]
Intellisense is the correct word 🙂

**Comment by punker76** [comment]
@raggnic v2.3.0 doesn’t include the latest icons. but you can also use the latest alpha to use the latest available icons. if you need the browser then you can download it from the appveyor or azure pipeline ci builds.

**Comment by raggnic** [comment]
Thank you @punker76 !
