### ISSUE TITLE
Add PICOL icons

### ISSUE THREAD

**Issue by timunie** [MahApps/MahApps.Metro.IconPacks#151]
**Is your feature request related to a problem? Please describe.**
Should we implement the PICOL-Icons? see: [http://picol.org](http://picol.org)
![image](https://user-images.githubusercontent.com/47110241/66651937-a0b23980-ec34-11e9-8679-a43024c55878.png)
*Just an impression*

**Describe the solution you'd like**
Implement the icons 

**Describe alternatives you've considered**
use other icons :-)

**Additional context**
I would try to implement them if you want me to. If not, just close this issue.

**Comment by punker76** [comment]
@timunie  this has now been added, and it will be released in the next version
