### ISSUE TITLE
How tu use IconPack on UWP Helpme Please

### ISSUE THREAD

**Issue by ZaJra** [MahApps/MahApps.Metro.IconPacks#153]
I'm new programing y i'm making a UWP proyect and I am just don't know how to use I tried many times and Spend a lot of Hours and i failed,Any one could send me an example or tell me hou to use ? Thanks very much.

**Comment by timunie** [comment]
Hi @ZaJra can you upload what you have so far? I will have a look then and see if I can guide you in the right direction. 

Happy cding
Tim

**Comment by timunie** [comment]
Hi @ZaJra,
this one works for me. [https://github.com/MahApps/MahApps.Metro.IconPacks/wiki/Sample-(WPF,-UWP)](https://github.com/MahApps/MahApps.Metro.IconPacks/wiki/Sample-(WPF,-UWP))

Happy coding
Tim
