### ISSUE TITLE
Icons display errors in XAML designer constantly though build works fine

### ISSUE THREAD

**Issue by panthernet** [MahApps/MahApps.Metro.IconPacks#154]
**Describe the bug**
When using the icons as described in FAQ a `xmlns:iconPacks="http://metro.mahapps.com/winfx/xaml/iconpacks"` namespace is generated automatically but XAML designer shows following error: 
`Unable to create unknown type "{http://metro.mahapps.com/winfx/xaml/iconpacks}PackIconMaterial"`
Project works when compiled but XAML designer don't show anything at all because of this error.

**To Reproduce**
^

**Expected behavior**
No XAML error displayed.

**Desktop Environment (please complete the following information):**
 - IconPacks Version: 3.0.0 Alpha
 - Visual Studio: 2019 16.3 Community
 - .NET Framework: Core 3.0 WPF

**Additional context**
Where's no error if I manually use several namespaces in the following format. Usable but not comfortable. 
```
        xmlns:iconPacks="clr-namespace:MahApps.Metro.IconPacks;assembly=MahApps.Metro.IconPacks.MaterialLight"
        xmlns:iconPacks1="clr-namespace:MahApps.Metro.IconPacks;assembly=MahApps.Metro.IconPacks.Material"
```

**Comment by punker76** [comment]
@panthernet Can you please specify which version of IconPacks, Visual Studio and .Net Core 3 you are using? Here is a screenshot from my test build with .Net Core 3.0 final, VS 16.3.5 and MahApps.Metro.IconPacks v3.0.0-alpha0245.

![2019-10-16_23h28_39](https://user-images.githubusercontent.com/658431/66960610-166f3880-f06d-11e9-9ab3-c9af50299920.png)

**Comment by panthernet** [comment]
Same lib version as yours. I'll try to update VS to latest minor patch to see if something is changing. Looks like the error is not 100% reproducable. Some controls use original namespace just fine but custom ContentControl with a style which uses this namespace produces the error steadily when referenced inside other control.

![image](https://user-images.githubusercontent.com/5926603/66966212-bd0f0580-f07c-11e9-962c-d3bf47ff659b.png)

![image](https://user-images.githubusercontent.com/5926603/66966258-de6ff180-f07c-11e9-830e-13d4f0fd31b2.png)

![image](https://user-images.githubusercontent.com/5926603/66966273-e9c31d00-f07c-11e9-924c-336dd4e00c19.png)

**Comment by panthernet** [comment]
Also don't forget to enable XAML UI designer when navigating MainWindow XAML code.

[SampleApp.zip](https://github.com/MahApps/MahApps.Metro.IconPacks/files/3738732/SampleApp.zip)

**Comment by punker76** [comment]
@panthernet I got it and will raise a PR. It's again the designer who can't handle generic classes.

![2019-10-17_21h34_50](https://user-images.githubusercontent.com/658431/67041911-f9973b80-f126-11e9-9432-30fc9411c1d6.png)
