### ISSUE TITLE
XamlParseException trying to bind PackIconControl.Kind

### ISSUE THREAD

**Issue by andreasgrosche** [MahApps/MahApps.Metro.IconPacks#156]
Binding the ``PackIconControl.Kind`` property results in a XamlParseException being thrown with  "A 'Binding' can only be set on a DependencyProperty of a DependencyObject".

I guess that the problem is [line 19 of the PackIconControl](https://github.com/MahApps/MahApps.Metro.IconPacks/blob/2c36725e038c0c3c8e53eb85d55c721444746a70/src/MahApps.Metro.IconPacks/PackIconControl.cs#L19) class where the parent type of the dependency property is set to ``PackIconBoxIcons`` instead of ``PackIconControl``.

**To Reproduce**
1. Use the PackIconControl in a WPF window binding the _kind_ to a property: ``<iconPacks:PackIconControl Kind="{Binding MyIcon}" Width="30" Height="30" />``
2. Provide the property in code behind: ``public PackIconSimpleIconsKind MyIcon => PackIconSimpleIconsKind.MySql; ``

**Expected behavior**
The icon is shown without any exception.

**Desktop Environment (please complete the following information):**
 - IconPacks Version: 3.0.0-alpha0253
 - Visual Studio: 2017

**Comment by punker76** [comment]
@andreasgrosche Thx for reporting this annoying copy&paste bug. It's fixed now.

**Comment by FCUnlimited** [comment]
Hi,

I've got exactly the same bug now.
VS 2019
Iconpacks.Evaicons 4.8.0

**Comment by punker76** [comment]
@FCUnlimited Please post the code how you use the control. This helps to understand what’s going wrong. If yo do this the please create a new issue. The optimal way is to create a sample app which shows this issue. Thx

**Comment by FCUnlimited** [comment]
Just finished the new issue then I saw the problem....it was me
I was using: `<iconPacks:EvaIcons Kind="{Binding Icon}" />` 
and not: `<iconPacks:PackIconEvaIcons Kind="{Binding Icon}" />`

Sorry for wasting your time :(
And thanks for your work!

**Comment by punker76** [comment]
@FCUnlimited Oh yes, the first one is the MarkupExtension which doesn't allow binding for the properties. Thx
