### ISSUE TITLE
PackIconExtension default size

### ISSUE THREAD

**Issue by ondrasvoboda** [MahApps/MahApps.Metro.IconPacks#165]
Hi,
I have just updated from version 2.3.0 to 3.1.0 and found out that icons created with PackIconExtension have default width and height set to 16 and these properties are not nullable. Thus setting icon size in styles is not working in WPF anymore (local value has higher priority).
Seems that this is related to commit 2c36725e038c0c3c8e53eb85d55c721444746a70. Is there any chance to fix this?

Thanks

**Comment by punker76** [comment]
@ondrasvoboda Do you mean the behavior when a global style is set in the App.xaml?

**Comment by ondrasvoboda** [comment]
@punker76 Yes

**Comment by punker76** [comment]
@ondrasvoboda Ok, I will look for a solution. The change comes from the UWP which doesn't allow nullable properties on MarkupExtension. As a workaround you can override this on the usage.

```xaml
<Button Content="{iconPacks:FontAwesome SpinnerSolid, Width=32, Height=32}" />
```

**Comment by ondrasvoboda** [comment]
@punker76 thanks, that would be great.
