### ISSUE TITLE
The cool MarkupExtension doesn't work anymore in WPF

### ISSUE THREAD

**Issue by timunie** [MahApps/MahApps.Metro.IconPacks#166]
**Describe the bug**
this is not possible with the new version: 

```xaml
<metro:WindowCommands>
    <Button Content="{iconPacks:PackIconMaterialDesign Kind=Help}" />
</metro:WindowCommands>
````

it throws;
```
Error XLS0505	Type 'iconPacks:PackIconMaterialDesign' is used like a markup extension but does not derive from MarkupExtension.
```

**To Reproduce**
1. Set up a new `MetroWindow`
2. Add a Button like shown above
3. try to compile -> It doesn't work 

**Expected behavior**
`{iconPacks:PackIconMaterialDesign Kind=Help}` should show me the `Icon`

**Screenshots**
![image](https://user-images.githubusercontent.com/47110241/71989557-2e9cc100-3232-11ea-932f-745a7ce55484.png)

**Desktop Environment (please complete the following information):**
 - IconPacks Version: 3.1.0
 - Visual Studio: 16.4.1
 - .NET Framework: 4.7.2

Happy coding,
Tim

**Comment by punker76** [comment]
@timunie That's correct, because this was changed in [v2.0](https://github.com/MahApps/MahApps.Metro.IconPacks/wiki/Breaking-change-1.9.x----2.0)

The [correct usage](https://github.com/MahApps/MahApps.Metro.IconPacks/wiki/MarkupExtensions#packicon-markupextensions-wpf-and-uwp) is now:

```xaml
<Button Content="{iconPacks:MaterialDesign Kind=Help}" />
```

**Comment by timunie** [comment]
Thank you @punker76 ,

yes this works. Two more questions:
1) why does Intellisense give me the other notation?
2) why does the IconBrowser this: `{iconPacks:PackIconBoxIcons Kind=LogosAirbnb}`?

Happy coding,
Tim

**Comment by punker76** [comment]
@timunie 

> 1. why does Intellisense give me the other notation?

I don't know.

> 2. why does the IconBrowser this: `{iconPacks:PackIconBoxIcons Kind=LogosAirbnb}`?

I'll fix this.

**Comment by timunie** [comment]
Hi @punker76 ,
point 1: I made a sample App for demo - and Intellisense works here. So I guess this is in cache or something like this. 

Sorry and Thanks,
Tim

**Comment by timunie** [comment]
Update: Just in case someone has the same issue: Cleaning the Solution and deleting all the `bin` and `obj` folders solved it for me.

Happy iconing,
Tim
