### ISSUE TITLE
Updating to 3.2.0 causes bad image build warning

### ISSUE THREAD

**Issue by Inzanit** [MahApps/MahApps.Metro.IconPacks#169]
**Describe the bug**
When upgrading from 3.0.1 to 3.2.0, the following warning is in the output of the build:

```
4>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Could not load file or assembly 'MahApps.Metro.IconPacks.MaterialLight.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.
```

**To Reproduce**
1. Start new WPF .NET Framework application
2. Install `MahApps.Metro.IconPacks`
3. Rebuild
4. Get warning

**Expected behavior**
1. Start new WPF .NET Framework application
2. Install `MahApps.Metro.IconPacks`
3. Rebuild
4. Successful build, no warnings

**Desktop Environment (please complete the following information):**
 - IconPacks Version: 3.2.0
 - Visual Studio: 2019 16.4.1
 - .NET Framework: 4.8

**Comment by mastorm** [comment]
C# Discord Gang was here

**Comment by punker76** [comment]
@Inzanit This is weird. I tried 2 scenarios but can't reproduce this warning/error.

First one with the `MahApps.Metro.IconPacks` NuGet package:

1. Start new WPF .Net 4.8 application
2. Install v3.0.1 of the `MahApps.Metro.IconPacks` NuGet package
3. Use `PackIconMaterialLight` control
```xaml
<iconPacks:PackIconMaterialLight Kind="Account" Width="32" Height="32" Margin="4" />
```
4. Start the application and close it directly (no warnings)
5. Update the `MahApps.Metro.IconPacks` NuGet package to v3.2.0
6. No warnings

Second one with the `MahApps.Metro.IconPacks.MaterialLight` NuGet package:

1. Start new WPF .Net 4.8 application
2. Install v3.0.1 of the `MahApps.Metro.IconPacks.MaterialLight` NuGet package
3. Use `PackIconMaterialLight` control
```xaml
<iconPacks:PackIconMaterialLight Kind="Account" Width="32" Height="32" Margin="4" />
```
4. Start the application and close it directly (no warnings)
5. Update the `MahApps.Metro.IconPacks.MaterialLight` NuGet package to v3.2.0
6. No warnings

My Environment is

- latest VS 2019 (stable)
- .Net Framework 4.8

**Comment by Inzanit** [comment]
I'm at a loss as to what this is - I explicitly installed the Material Light package and now am I receiving this compilation error:

![image](https://user-images.githubusercontent.com/1341180/73842035-bcf56a00-4813-11ea-93b3-72d8991089fc.png)

This only happens on 3.2.0 @punker76 any way I could provide better overview of what this could be? I'm looking through the verbose MSBuild log, but there isn't anything that sticks out.

Running on 3.1.0 works without warning. 3.2.0 _does_ work, but there is an MSBuild warning.

**Comment by punker76** [comment]
@Inzanit Can you provide this simple sample here on GitHub?

**Comment by Inzanit** [comment]
I apologise @punker76, IRL things came in the way. I diagnosed this myself, and it seems something went wrong in my `.nuget` folder. I deleted the folder and let VS restore all packages - the issue is now resolved. Apologies, again.
