### ISSUE TITLE
Improve new icon logo

### ISSUE THREAD

**Issue by timunie** [MahApps/MahApps.Metro.IconPacks#174]
**Describe the bug**
Icon improvements

**To Reproduce**
See the latest master-branch

**Expected behavior**
- Use the Icon #96 for the Browser as well
- improve appearance for low resolution Icons (see Screeshot)

**Screenshots**
![image](https://user-images.githubusercontent.com/47110241/74180254-7b175a00-4c3f-11ea-979d-1827f5d4e1ca.png)

magnified:
![image](https://user-images.githubusercontent.com/47110241/74180335-9f733680-4c3f-11ea-973f-9651c1ed42c9.png)

**Desktop Environment (please complete the following information):**
 - IconPacks Version: v2.3.0
 - Visual Studio:  2019 16.4
 - .NET Framework: independent

**Repo**
None

**Additional context**
@Templarian maybe you can provide the svg for the sticker (@punker76 decided that this should be the icon 😄 ), I can create different resolution pngs and an *.ico-File then.

Happy coding, 
Tim

**Comment by Templarian** [comment]
@timunie I'm busy at work, but if your software supports PDF import you can grab it from https://github.com/MahApps/MahApps.Metro.IconPacks/issues/96#issuecomment-577029843

**Comment by jizc** [comment]
I love the new icon, but yeah, my two cents are also that the low resolution version could be better, and personally I prefer the gradient from [#96 (comment)](https://github.com/MahApps/MahApps.Metro.IconPacks/issues/96#issuecomment-577029843), where the light shines from the top-left.

**Comment by timunie** [comment]
@Templarian Inkscape was able to import the PDF. Thank you
@jizc I used the original gradient. Let's see if @punker76 is happy with it.

ref: #175 

Happy coding,
Tim
