### ISSUE TITLE
It is not possible to evaluate the expression [System.IO.Path]::GetDirectoryName

### ISSUE THREAD

**Issue by stefanobenedetti88** [MahApps/MahApps.Metro.IconPacks#180]
Hello,
I'm trying to open the source code and compile it with vs2019, but all the projects are not loaded, and report the following error:
"it is not possible to evaluate the expression [System.IO.Path]::GetDirectoryName invalid path format. <my nuget path>".
Can you help me?
Thanks.

**Comment by punker76** [comment]
@stefanobenedetti88 Do you have the .Net Core 3.1 SDK installed? [wiki](https://github.com/MahApps/MahApps.Metro.IconPacks/wiki/How-to-build-the-solution)

**Comment by stefanobenedetti88** [comment]
Thanks, now works!
