### ISSUE TITLE
Make the Brush bindable 

### ISSUE THREAD

**Issue by audacity76** [MahApps/MahApps.Metro.IconPacks#182]
I'd like to change the icon color to the foreground color of the surrounding control. As the foreground color changes dynamically, I need to bind the icon brush color. Currently this is not possible. Any thoughts on this?

**Comment by punker76** [comment]
@audacity76 Here is an example with the MahApps Button style, but it should work also with a normal style or any other Control which can set the Foreground.

```xaml
<Button Foreground="Crimson"
        Margin="10 5">
    <Button.Content>
        <iconPacks:PackIconMaterial Width="20"
                                  Height="20"
                                  Kind="Cookie" />

    </Button.Content>
</Button>
```

```xaml
<Button Foreground="Crimson"
        Margin="10 5"
        Content="{iconPacks:Material Cookie, Width=20, Height=20}" />
```

![image](https://user-images.githubusercontent.com/658431/75550956-53900200-5a33-11ea-9dad-6a24f81ae19e.png)

**Comment by audacity76** [comment]
Thanks for the hint. I was using the converter to bind to an image source. The color then defaults to black:

```
<Image DataContext="{Binding Icon}"
       Source="{Binding Converter={iconPacks:PackIconMaterialKindToImageConverter}}"
       Height="14" Width="14"/>
```

Simply changed it as you suggested and the color of the foreground is used:

```
<iconPacks:PackIconMaterial Kind="{Binding Icon}"
                            Width="14"
                            Height="14" />
```
