### ISSUE TITLE
Need to Bundle All IconPacks?

### ISSUE THREAD

**Issue by ekarkosApollo** [MahApps/MahApps.Metro.IconPacks#183]
**Is your feature request related to a problem? Please describe.**
I'm working on building a final version of the product I'm working on which utilizes MahApps Metro IconPacks. My application only uses the FontAwesome and Material icon packs but I noticed that I need every IconPack DLL for the application to run. This is very annoying since I am required to include unnecessary DLLs in my application's install for icon packs that the application doesn't use.

**Describe the solution you'd like**
Only need to include DLLs for IconPacks being used.

**Describe alternatives you've considered**
At the moment I've downgraded to version 2.3.0 since that includes both FontAwesome and Material but it would be nice if this was a feature so I can start using the newer versions again.

**Additional context**
Not really, love this library and it's been great to use during development of my application!

**Comment by punker76** [comment]
@ekarkosApollo You can also use only the NuGet packages for this 2 Icon Packs. 

So de-install the all-in IconPacks NuGet package and use only these 2 ones

- https://www.nuget.org/packages/MahApps.Metro.IconPacks.FontAwesome/
- https://www.nuget.org/packages/MahApps.Metro.IconPacks.Material/

**Comment by ekarkosApollo** [comment]
Ah perfect I hadn't seen that before... Thanks!

**Comment by punker76** [comment]
@ekarkosApollo np. The wiki should help here (I hope so) https://github.com/MahApps/MahApps.Metro.IconPacks/wiki/Install

**Comment by Azhe403** [comment]
Single .dll for all icons may look good!

![gambar](https://user-images.githubusercontent.com/17938038/79042128-4c0d6c80-7c1f-11ea-8b1c-d91e4c189763.png)

**Comment by timunie** [comment]
Hi @Azhe403 ,

as @punker76 already mentioned you can just install the ones you need. I really like the flexibility here and I don't see a need to change this. If you don't want to ship too much files to the customer just select the ones you need or ship a single exe-File. 

Happy coding,
Tim
