### ISSUE TITLE
PackIconControlDataFactory missing PICOL Icons

### ISSUE THREAD

**Issue by jacob7690** [MahApps/MahApps.Metro.IconPacks#188]
Hello,

The PackIconControlDataFactory does not add icons from PackIconPicolIconsDataFactory.  The class says it is auto generated and not to amend so I'm not entirely sure what needs to be done.  However it is generated, I think that the `internal static IDictionary<Enum, string> Create()` method just needs the following code added it to it:

```
foreach (var packIcon in PackIconPicolIconsDataFactory.Create())
{
    dictionary.Add(packIcon.Key, packIcon.Value);
}
```

**Comment by punker76** [comment]
@jacob7690 this has now been fixed, and it will be released in the next version.
