### ISSUE TITLE
Enable search in multiple packs.

### ISSUE THREAD

**Issue by igorushi** [MahApps/MahApps.Metro.IconPacks#20]
When I use the browser to find an icon I usually search in multiple icon packs. On each tab I need to enter a search string again. It would be nice to preserve a search term among tabs or maybe have an aggregated "all packs" tab.

**Comment by punker76** [comment]
@igorushi Done in 20a574c9dc0c3c4d9bf0254e212431aa9594ee6c and will be available in 1.5.0
