### ISSUE TITLE
About PackIconModernKind.ConnectionQuality ICOs display error

### ISSUE THREAD

**Issue by LuGuangguang** [MahApps/MahApps.Metro.IconPacks#200]
Hello,My studio is Using VS 2019, .NET CORE 3.1 , MahApps.Metro.IconPacks 4.0.0.0 
When I  Creat PackIconModernKind.ConnectionQuality ICOs,It's  not correct.

![图片](https://user-images.githubusercontent.com/34500722/81661882-5e253980-946f-11ea-82b7-62e3259fef1f.png)

Please have a look, thank you

**Comment by jizc** [comment]
The problem here is that those icons are supposed to be two-toned, which is something this library currently doesn't support.

**Comment by LuGuangguang** [comment]
> 
> 
> The problem here is that those icons are supposed to be two-toned, which is something this library currently doesn't support.

I see,thanks a lot
