### ISSUE TITLE
Not able to change PackIconControl Kind in triggers at runtime

### ISSUE THREAD

**Issue by DaaWaan** [MahApps/MahApps.Metro.IconPacks#201]
**Describe the bug**
I am trying to change the `Kind` of a PackIconControl when it is hovered by a mouse using `Triggers`. Unfortunately, the Control doesn't update at runtime. There is no problem however when I'm going to change the `Kind` inside the EventHandlers for the MouseOver.

**To Reproduce**
1. Just simply add a `Style` with `Style.Triggers` that has a trigger for the IsMouseOver behavior. Here's a sample code I made:
```xml
<maicons:PackIconControl Width="18" Background="Azure" Height="18" Kind="{x:Static maicons:PackIconEvaIconsKind.Menu}">
    <maicons:PackIconControl.Style>
        <Style TargetType="{x:Type maicons:PackIconControl}">
            <Style.Triggers>
                <Trigger Property="IsMouseOver" Value="True">
                    <Setter Property="Foreground" Value="Yellow"/>
                    <Setter Property="Kind" Value="{x:Static maicons:PackIconEvaIconsKind.ArrowBack}"/>
                </Trigger>
            </Style.Triggers>
         </Style>
    </maicons:PackIconControl.Style>
</maicons:PackIconControl>
```

**Expected behavior**
Both the `Foreground` and the `Kind` should be changed when the mouse is hovered. Only foreground is changing when it is hovered.

**Desktop Environment:**
 - IconPacks Version: [v4.0.0]
 - Visual Studio: [2019 16.5.5]
 - .NET Framework: [4.5.2]

**Comment by DaaWaan** [comment]
I didn't notice I was setting the `Kind` locally

**Comment by punker76** [comment]
@DaaWaan 👍  You should also derive from the base Style like

```xaml
<Style TargetType="{x:Type maicons:PackIconControl}" BasedOn="{x:Type maicons:PackIconControl}">

</Style>
```

**Comment by DaaWaan** [comment]
Oh right, thanks!
