### ISSUE TITLE
"Emtpy" or "None" Icon Kinds

### ISSUE THREAD

**Issue by chintal** [MahApps/MahApps.Metro.IconPacks#209]
**Is your feature request related to a problem? Please describe.**

I'm using MahApps IconPacks (specifically, Material) in a WFP application. I bind the "Kind" attribute to code in the background to change the Icon as I need it, and this works great. However, in addition to 3-4 icons, I also want one of the states for there to be no icon. Sending in an empty string / null through the binding works, but does so because exceptions are swallowed up in the background. While I wouldn't otherwise mind this, it has the unfortunate side effect of filling up my debug window with exceptions.

**Describe the solution you'd like**
I'd like to able to set the Kind to "Blank" or "Empty" or "None" or "Null" and would like the icon to simply be blank. Everything else staying the same, including icon size, general structure and behavior. 

**Describe alternatives you've considered**
The only alternative I can think of is to add Icon IsVisible to the Model / ViewModel, and use some random Kind for the case where the Icon needs to actually disappear. This should work. I will probably implement in this manner for the moment. I already do something similar to set the icon foreground. It would be nice to not have to add yet another binding for this use case, though. 

**Additional context**
I'm using the icons to show derivatives of a network connection - the icon becomes relevant only after a connection is established and can have multiple states.

**Comment by timunie** [comment]
> I already do something similar to set the icon foreground

Maybe you can also set the Foreground to `Transparent` for now (I know it is a workaround).

**Comment by punker76** [comment]
@chintal All icon packs contains already an "Empty placeholder" enum kind.

https://github.com/MahApps/MahApps.Metro.IconPacks/blob/51ad80a5ce56677560cf753f5a6a3c2636562687/src/MahApps.Metro.IconPacks/PackIconMaterialKind.cs#L20

**Comment by chintal** [comment]
Exactly what I was looking for. Thank you!
