### ISSUE TITLE
'Kind' property was already registered by 'ControlzEx_PackIconBase`1_14_190585527'

### ISSUE THREAD

**Issue by khteh** [MahApps/MahApps.Metro.IconPacks#22]
![mahappsiconpacksexception](https://cloud.githubusercontent.com/assets/3871483/19685777/bd9a5a52-9af0-11e6-8256-3661e6f4e241.png)
Any advice and insight is appreciated

**Comment by punker76** [comment]
@khteh Can you post your Xaml code of the PackIcon?

**Comment by punker76** [comment]
@khteh ?

**Comment by khteh** [comment]
@punker76, please find attached my .XAML. Thanks.

**Comment by khteh** [comment]
`<UserControl x:Class="OmniInteger.GUI.View.SessionControl"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:local="clr-namespace:OmniInteger.GUI.View"
            xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
            xmlns:iconPacks="http://metro.mahapps.com/winfx/xaml/iconpacks"
            xmlns:Dialog="clr-namespace:MahApps.Metro.Controls.Dialogs;assembly=MahApps.Metro"
            xmlns:i="http://schemas.microsoft.com/expression/2010/interactivity"
            xmlns:prism="clr-namespace:Microsoft.Practices.Prism.Interactivity;assembly=Microsoft.Practices.Prism.Interactivity"
             mc:Ignorable="d" d:DesignWidth="300" Height="202">
    <UserControl.Resources>
        <ResourceDictionary>
            <Thickness x:Key="ControlMargin">0 5 0 0</Thickness>
        </ResourceDictionary>
    </UserControl.Resources>
    <i:Interaction.Triggers>
        <i:EventTrigger EventName="Closing">
            <prism:InvokeCommandAction Command="{Binding CloseCommand}"/>
        </i:EventTrigger>
    </i:Interaction.Triggers>
    <Grid HorizontalAlignment="Left" Height="224" Margin="0,5,0,-27" VerticalAlignment="Top" Width="280">
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="9*"/>
            <ColumnDefinition/>
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition Height="233*"/>
            <RowDefinition Height="24*"/>
        </Grid.RowDefinitions>
        <Label x:Name="lblCountry" Content="Country:" HorizontalAlignment="Left" Margin="10,10,0,0" VerticalAlignment="Top"/>
        <ComboBox x:Name="cboCountry" IsEditable="false" ItemsSource="{Binding Countries}" SelectedItem="{Binding Country, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" HorizontalAlignment="Left" Margin="70,10,0,0" VerticalAlignment="Top" Width="120"/>
        <Label x:Name="lblMission" Content="Mission: " HorizontalAlignment="Left" Margin="10,41,0,0" VerticalAlignment="Top"/>
        <ComboBox x:Name="cboMission" IsEditable="{Binding IsMissionEditable, Mode=TwoWay}" ItemsSource="{Binding Missions}" SelectedItem="{Binding Mission, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" DisplayMemberPath="Description" SelectedValuePath="Description" SelectedValue="{Binding Path=Description, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" Text="{Binding MissionText, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" HorizontalAlignment="Left" Margin="10,67,0,0" VerticalAlignment="Top" Width="120"/>
        <Label x:Name="lblLocation" Content="Location: " HorizontalAlignment="Left" Margin="138,41,0,0" VerticalAlignment="Top"/>
        <ComboBox x:Name="cboLocation" IsEditable="{Binding IsLocationEditable, Mode=TwoWay}" ItemsSource="{Binding Locations}" SelectedItem="{Binding Location, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" DisplayMemberPath="Description" SelectedValuePath="Description" SelectedValue="{Binding Path=Description, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" Text="{Binding LocationText, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" HorizontalAlignment="Left" Margin="138,67,0,0" VerticalAlignment="Top" Width="120" Grid.ColumnSpan="2"/>
        <Button x:Name="btnNewMission" Command="{Binding NewMission}" HorizontalAlignment="Left" Margin="10,94,0,0" Style="{DynamicResource SquareButtonStyle}" VerticalAlignment="Top" Width="75" Height="30">
            <iconPacks:PackIconMaterial Kind="NewBox" ToolTip="New Mission"/>
        </Button>
        <Button x:Name="btnDeleteMission" Command="{Binding DeleteMission}" HorizontalAlignment="Left" Margin="10,124,0,0" Style="{DynamicResource SquareButtonStyle}" VerticalAlignment="Top" Width="75" Height="30">
            <iconPacks:PackIconMaterial Kind="Delete" ToolTip="Delete Mission"/>
        </Button>
        <Button x:Name="btnDeleteLocation" Command="{Binding DeleteLocation}" HorizontalAlignment="Left" Margin="183,124,0,0" Style="{DynamicResource SquareButtonStyle}" VerticalAlignment="Top" Width="75" Grid.ColumnSpan="2" Height="30">
            <iconPacks:PackIconMaterial Kind="Delete" ToolTip="Delete Location"/>
        </Button>
        <Button x:Name="btnNewLocation" Command="{Binding NewLocation}" HorizontalAlignment="Left" Margin="183,94,0,0" Style="{DynamicResource SquareButtonStyle}" VerticalAlignment="Top" Width="75" Grid.ColumnSpan="2" Height="30">
            <iconPacks:PackIconMaterial Kind="NewBox" ToolTip="New Location"/>
        </Button>
        <Button x:Name="btnSave" Command="{Binding Save}" HorizontalAlignment="Left" Margin="10,154,0,0" Style="{DynamicResource SquareButtonStyle}" VerticalAlignment="Top" Width="75" Grid.RowSpan="1" Height="30">
            <iconPacks:PackIconMaterial Kind="ContentSave" ToolTip="Save"/>
        </Button>
        <Button x:Name="btnOK" Content="OK" Command="{Binding ExitCommand}" Margin="97,154,80,0" VerticalAlignment="Top" Height="30" RenderTransformOrigin="0.502,1.069"/>
        <Button x:Name="btnExit" ToolTip="Exit Application" Command="{Binding QuitCommand}" HorizontalAlignment="Left" Margin="183,154,0,0" Style="{DynamicResource SquareButtonStyle}" VerticalAlignment="Top" Width="75" Height="30" RenderTransformOrigin="0.493,-0.787" Grid.RowSpan="1" Grid.ColumnSpan="2">
            <iconPacks:PackIconMaterial Kind="ExitToApp" ToolTip="Quit"/>
        </Button>
    </Grid>
</UserControl>`

**Comment by punker76** [comment]
@khteh Which version of MahApps.Metro and MahApps.Metro.IconPacks do you use? Which VS version is this?

**Comment by khteh** [comment]
VS 2015
MahApps.Metro: 1.4.0.0
MahApps.Metro.IconPacks: 1.4.0.0

**Comment by punker76** [comment]
@khteh What is your selected solution platform for your app? Is it maybe different to `Any CPU`?

**Comment by khteh** [comment]
x64. I tried Any CPU but have problem detecting my MS Unit Tests in test explorer.

**Comment by punker76** [comment]
@khteh Problem is, that I can't reproduce this issue. I've chatted with another guy with the same problem. I don't really know why this issue happens with different solution platforms, I will investigate it...

**Comment by khteh** [comment]
I just switched to Any CPU but the same exceptions persist.

**Comment by punker76** [comment]
@khteh It's Designer related stuff so you shoudl delete all obj/bin folders and the Designer shadow cache... close VS and start again...

**Comment by khteh** [comment]
@punker76 That works. Thanks!

**Comment by Pablokiryu** [comment]
Also Solved it for me. 
I was Running VS Community 2019 V. 16.3.10 and MahApps.Metro.1.6.5 and MahApps.Metro.IconPacks.2.3.0
Thank you very much
