### ISSUE TITLE
Create a Social card

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro.IconPacks#225]
### Describe the request
This library hasn't a nice social card which can be used in social networks.

### Expected behavior
Upload an image with these specication:

Images should be at least 640×320px (1280×640px for best display).

![repository-open-graph-template](https://user-images.githubusercontent.com/658431/94988799-262ea800-0570-11eb-9dbc-da81829871bc.png)

### Additional note
This card should contain the icon for this library.

![](https://raw.githubusercontent.com/MahApps/MahApps.Metro.IconPacks/develop/resources/logo_big.png)

**Comment by AlexGipp** [comment]
Hey, where should i put the finished card? (can i just put it in the resources folder?)

**Comment by punker76** [comment]
@AlexGipp Yes, of course! 👍

**Comment by AlexGipp** [comment]
I just opened a pr, will probaby add more cards later on.
If you have any feedback please let me know. ^^
