### ISSUE TITLE
Idea for some improvements of the IconPack-Browser

### ISSUE THREAD

**Issue by timunie** [MahApps/MahApps.Metro.IconPacks#230]
**Is your feature request related to a problem? Please describe.**
IMO the current implementation of the IconPacksBrowser is great, but has some limitations:
- The more IconPacks are added the more space is needed by the TabHeader. Searching for a specific IconPack gets "harder"
- The "All"-tab does not optically separate form the other tabs
- There is not much space left for new features, such as
   - Displaying the Hyperlink #228 
   - Add more Export options #57 #12 

**Describe the solution you'd like**
Maybe using a `HamburgerMenu` instead of `TabControl` needs less space and the `All`-Items can be shown after a `Separator`. The new free space can be used to have an advanced Preview Pane with additional export options, such as
- Selecting a `Color`
- Setting the `Size`
- Export the icon e.g. as `*.png, *.bmp, *.ico` and `*.svg`
- Optional: Create a Settings-Page

**Describe alternatives you've considered**
Leave it as it is now

**Additional context**
I have an idea in my mind and will show it soon. If the idea is accepted, it can be adjusted in detail

**Comment by pdm19882004** [comment]
I am working on a similar project.
https://github.com/MahApps/MahApps.Metro.IconPacks/issues/238#issuecomment-707828444
