### ISSUE TITLE
Strong name signing the nuget packages

### ISSUE THREAD

**Issue by Alkalinee** [MahApps/MahApps.Metro.IconPacks#24]
Hey,
it would be awesome if the nuget packages would be strong name signed (for obvious reasons).

**Comment by punker76** [comment]
@Alkalinee Please try this one https://github.com/MahApps/MahApps.Metro.IconPacks#strong-naming

**Comment by Alkalinee** [comment]
I already tried that and got this runtime exception:
```
Additional information: Beim Festlegen der Eigenschaft "System.Windows.ResourceDictionary.DeferrableContent" wurde eine Ausnahme ausgelöst.

{"Die Datei oder Assembly \"MahApps.Metro.IconPacks.Material, PublicKeyToken=null\" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)":"MahApps.Metro.IconPacks.Material, PublicKeyToken=null"}
```

(Yes, StrongNamer is working, no idea why he wants to find the unsigned assembly. I already tried a rebuild and a another tool: Brutal.Dev.StrongNameSigner, same result)

Anyways, got it working by compiling the project by myself with a strong name, seems like xaml has a problem with afterwards strongnaming.

**Comment by punker76** [comment]
@Alkalinee I will check why it's not working later.
