### ISSUE TITLE
Create a short Wiki

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro.IconPacks#25]
Create a short Wiki from the already existing README with some simple examples.

**Comment by amkuchta** [comment]
I can tackle this one, @punker76. It's the least I can do so I don't feel like a free loader :laughing:

**Comment by amkuchta** [comment]
Three pages up for your review, @punker76 .  I mainly used the same info from the `README.md`, but added a few small touches and broke it out into a few different pages that made sense.  If you want anything changed, let me know.

**Comment by punker76** [comment]
@amkuchta Thank you very much! 👍

**Comment by amkuchta** [comment]
@punker76 not a problem, my pleasure!  It's the least I can do!
