### ISSUE TITLE
Icon not visible in designer 

### ISSUE THREAD

**Issue by mady005** [MahApps/MahApps.Metro.IconPacks#251]
as the title says the icon is not visible in the designer view but visible when I run the app

**Comment by punker76** [comment]
@mady005 Which icon?

**Comment by mady005** [comment]
any kind.
<iconPacks:PackIconFeatherIcons
                                                                        HorizontalAlignment="Center" 
                                                                        VerticalAlignment="Center" Kind="Search"
                                                                        Height="16" Margin="3,7,200,7"
                                                                        Width="20" />

**Comment by punker76** [comment]
@mady005 Which IconPacks version? Please provide also a full sample. Thx

**Comment by mady005** [comment]
I'm using the latest version 4.8.0
https://prnt.sc/vb7vrd
I tried closing and reopening the designer but it's still not visible

**Comment by punker76** [comment]
@mady005 Must be something different...

![image](https://user-images.githubusercontent.com/658431/97805844-c7d11400-1c58-11eb-9a29-a26e858d0abd.png)

**Comment by punker76** [comment]
@mady005 Wrong Background?

**Comment by mady005** [comment]
could be I don't know what's wrong I tried changing the background but no luck

**Comment by mady005** [comment]
Main window

Title="test" AllowsTransparency="True"
        Height="800"
        Width="1200"
        WindowStyle="None"
        WindowStartupLocation="CenterScreen"
        Background="{x:Null}"
        MouseDown="Window_MouseDown" 
        Opacity="0.99"

    <Border Background="White">
            <iconPacks:PackIconFeatherIcons
                                                                        HorizontalAlignment="Center" 
                                                                        VerticalAlignment="Center" Kind="Search"
                                                                        Height="16" Margin="61,8,1119,776"
                                                                        Width="20" Foreground="White" />
        </Border>

**Comment by mady005** [comment]
<Grid>
        <Border Background="White">
            <iconPacks:PackIconFeatherIcons
                                                                        HorizontalAlignment="Center" 
                                                                        VerticalAlignment="Center" Kind="Search"
                                                                        Height="16" Margin="61,8,1119,776"
                                                                        Width="20" Foreground="White" />
        </Border>
    </Grid>

**Comment by punker76** [comment]
@mady005 Your Background and Forground set to White!

**Comment by mady005** [comment]
yes but i created that test app it's still the same in my main

**Comment by mady005** [comment]
my main app border is style is dynamic https://prnt.sc/vb8489 which is set to color https://prnt.sc/vb84fc

**Comment by mady005** [comment]
https://prnt.sc/vb85o6 https://prnt.sc/vb85s2

**Comment by punker76** [comment]
@mady005 Then set the Foreground of the iconPacks:PackIconFeatherIcons to White, or something different to the Background.

**Comment by punker76** [comment]
@mady005 Seems like a bug with the VS designer. Which VS version is this?

**Comment by mady005** [comment]
It's 2019 not sure about the exact version, I'm updating it now

**Comment by mady005** [comment]
The issue is solved after updating the VS
