### ISSUE TITLE
Icon not shown in designer

### ISSUE THREAD

**Issue by gnimor** [MahApps/MahApps.Metro.IconPacks#253]
I am using the Mahapps iconpack in my application. I have the following code in XAML:

                <Button Width="Auto" Height="70"
                        HorizontalAlignment="Center" VerticalAlignment="Center"
                        Command="{Binding LoadCommand}" IsEnabled="{Binding CanLoad}"
                        Name="loadUnitBtn" Padding="20,1">

                    <StackPanel Orientation="Vertical">
                        <iconPacks:PackIconOcticons Width="33" Height="33"
                                                    Margin="3" Kind="Rocket" />
                        <AccessText Margin="0,0,0,3" HorizontalAlignment="Center"
                                    VerticalAlignment="Center" Text="_Load" />
                    </StackPanel>

                </Button>

But in the designer I get a blank area. Running the application shows the icon as expected:

![image](https://user-images.githubusercontent.com/14901306/102181495-f9213e80-3eaa-11eb-8019-44c7f9e0c799.png)

I am using the following packages:

```
  <package id="MahApps.Metro.IconPacks.FontAwesome" version="4.8.0" targetFramework="net472" />
  <package id="MahApps.Metro.IconPacks.Material" version="4.8.0" targetFramework="net472" />
  <package id="MahApps.Metro.IconPacks.Octicons" version="4.8.0" targetFramework="net472" />
```

and Visual Studio 2019 16.8.3

**Comment by timunie** [comment]
Hi @gnimor 

please try to enable one of these buttons:
![image](https://user-images.githubusercontent.com/47110241/102248882-01f12f00-3f02-11eb-8dd9-0872abb14c6a.png)

Sometimes the visual studio designer is buggy for custom controls, but there is not much we can do about it 😒 . 

Happy coding
Tim

**Comment by bluebright** [comment]
Hi @gnimor 
How about set solution platform to "Any CPU" temporary?
When I changed from "x64" to "Any CPU", the icon was visible. in "visual studio 2017" 15.9.30.

### Case "x64"
![Case x64](https://user-images.githubusercontent.com/12007202/106828943-86745880-66ce-11eb-9a23-9aed05053442.PNG)

### Case "Any CPU"
![Case any cpu](https://user-images.githubusercontent.com/12007202/106828949-8a07df80-66ce-11eb-9af2-a378cd9b702d.PNG)

**Comment by punker76** [comment]
I'm aware of Visual Studio Designer bugs but will not look for it, except it's really a bug inside this lib.
