### ISSUE TITLE
Draw icons using win2d

### ISSUE THREAD

**Issue by jtorjo** [MahApps/MahApps.Metro.IconPacks#260]
**Is your feature request related to a problem? Please describe.**

First of all, you rock! Been using this for close to 2 years now 😁

I'd like to be able to print the icons usin win2d. Win2d has a way to also create a Path, which I can then draw on the screen. Each of the icons has a `Path` conterpart (like, `PathIconMaterial`), so I assume it would be possible to create a win2d path for each.

Is this possible? 
Is this somewhere on your roadmap?
Anything to point me in the right direction (if it's not that difficult, I guess I could take a stab at it) ?

**Comment by timunie** [comment]
Hi @jtorjo 

let me give you a few answers, even if I am not the owner of this package:

> Is this possible?

Yes, I think this is possible, At least I think you can copy the path data from the browser and paste it manually into your App. 

> Is this somewhere on your roadmap?

No, as this is a free time project, work is done when work is done. 

> Anything to point me in the right direction (if it's not that difficult, I guess I could take a stab at it) ?

It is open source, so clone yourself the source, create a new branch and see what's going on. Here you find a few more infos on how to build the solution: https://github.com/MahApps/MahApps.Metro.IconPacks/wiki/How-to-build-the-solution

Happy coding
Tim

**Comment by jtorjo** [comment]
> Yes, I think this is possible, At least I think you can copy the path data from the browser and paste it manually into your App.

Yeah, basically if that is somehow available, indeed, I should be able to figure it out. Thanks!
