### ISSUE TITLE
IconPack in UWP Causes Designer to Fail

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro.IconPacks#27]
Utilizing the IconPack Nuget package, VS2015 designer crashes and fails to restart.  It is worth noting that the application builds fine - designer is the only item that is having issues.  The error output I am given is as follows:

```
System.Runtime.Remoting.RemotingException
[13836] Designer process terminated unexpectedly!
```

The actual issue does not arise until I actually use an icon:

```xaml
<IconPack:PackIconMaterial Kind="Settings" />
```

Simply placing the `using` statement raises no issues.

**Comment by punker76** [comment]
@amkuchta I figured out this happens if you select `x64` for the Platform. I got no problems with `x86` or `Any CPU`. Tested with this [sample](https://github.com/punker76/IconPacksTestApp).

**Comment by punker76** [comment]
@amkuchta And this is maybe the explanation http://stackoverflow.com/a/5379908/920384

**Comment by amkuchta** [comment]
Apparently my comment never took... using `x86` solved my issue, I don't know if you want to close this issue or not, given that this is only a work-around, but it appears that the issue is within VS and not `IconPacks` itself.

**Comment by amkuchta** [comment]
Also (once again), thank you.  Your work is vastly helpful, impressive, and greatly appreciated!
