### ISSUE TITLE
Constructor Error when using MarkupExtension

### ISSUE THREAD

**Issue by eluchsinger** [MahApps/MahApps.Metro.IconPacks#28]
I get the following error:
> The type "PackIconFontAwesomeExtension" does not include a constructor that has the specified number of arguments.

When I try to use the following demo material (using the Markup Extension in WPF):
`<Button Content="{iconPacks:PackIconFontAwesome StarOutline}" />`

My Visual Studio Designer shows an Invalid Markup error message also.

My workaround right now is to use the general ("generic") markup extension:
`Content="{iconPacks:PackIcon  {x:Static iconPacks:PackIconModernKind.Settings}}" />`

Can you check, if you can reproduce this error?

**Comment by punker76** [comment]
@eluchsinger Which NuGet package do you use?

**Comment by eluchsinger** [comment]
The general one, it should be. I will check and report back as soon as possible.

**Comment by punker76** [comment]
@eluchsinger This should work (self-tested™ with a clean project). Make sure you use the latest version. Also clean bin/obj folders and make a rebuild.

**Comment by eluchsinger** [comment]
MahApps.Metro.IconPacks, v1.6.0

I don't know, weird. Maybe you can see something? If not, I will just work around it.

![iconpack error](https://cloud.githubusercontent.com/assets/12324017/20639974/82786fc6-b3d3-11e6-826c-e1ef2b1a75d3.png)

**Comment by punker76** [comment]
@eluchsinger Is this project public? So I can take a look to the complete situation. Which target do you use? AnyCPU, x86, x64?

**Comment by eluchsinger** [comment]
@punker76 it's not public, but I can give you access to the repo. I target AnyCPU. It's just a demo project in the university, and I am testing out new stuff.

**Comment by punker76** [comment]
@eluchsinger Thx for the access to the project! I cloned it and restored the NuGet packages. After that I added the Button from your screenshot... and it works 🙈 

![2016-11-27_11h41_49](https://cloud.githubusercontent.com/assets/658431/20647532/c4ecbf2e-b496-11e6-8f8c-b7a8c39bad2f.png)

So another try could be by deleting all your downloaded packages and restore it again. Maybe there is a wrong reference to an old version of IconPacks or whatever...

![2016-11-27_11h45_05](https://cloud.githubusercontent.com/assets/658431/20647541/fb1d7714-b496-11e6-8a4b-d3c870c08b62.png)

Sometimes it's also good to delete the designer ShadowCache folder

`C:\Users\<USER>\AppData\Local\Microsoft\VisualStudio\14.0\Designer\ShadowCache`

**Comment by eluchsinger** [comment]
Hmm weird effect. Ok I will try that. Thanks for the help though!

**Comment by eluchsinger** [comment]
Ok. I deleted the designer ShadowCache Folder and it worked! I will remember that trick for the next time. Thanks!
