### ISSUE TITLE
Designer error in a 'custom' style 'Setter' for an icon

### ISSUE THREAD

**Issue by gigios** [MahApps/MahApps.Metro.IconPacks#29]
The title of the issue is not clear, sorry for this.
I'm using the last version of the IconPacks (1.6.0) and I have tried to change directly the 'ButtonsExample.xaml' file in the 'MahApps.Metro.Demo.Shared' to replicate my problem.

I have the necessity to change an Icon when change a property. To do this I have set an 'inline' style for the icon with a DataTrigger to change the 'Kind' property to the desired icon.
This is my code (I have added a checkbox with an icon as content, and I want to change the icon when change the IsChecked property of the checkbox):
```xml
  <CheckBox Margin="{StaticResource ControlMargin}" IsChecked="True">
    <iconPacks:PackIconModern>
      <iconPacks:PackIconModern.Style>
        <Style TargetType="{x:Type iconPacks:PackIconModern}">
          <Setter Property="Kind" Value="Check" />
          <Style.Triggers>
            <DataTrigger Binding="{Binding IsChecked, RelativeSource={RelativeSource AncestorType=CheckBox}}" Value="False">
              <Setter Property="Kind" Value="Close" />
            </DataTrigger>
          </Style.Triggers>
        </Style>
      </iconPacks:PackIconModern.Style>
    </iconPacks:PackIconModern>
  </CheckBox>
```
With this 'code' the Designer mark the **Property="Kind"** as wrong with the message:  
`The property "Kind" is not a DependencyProperty. To be used in markup, non-attached properties must be exposed on the target type with an accessible instance property "Kind".`  
(In my project the error is: **the member "Foreground" is not recognized or is not accessible** (this because I have tried to change the foreground color in the datatrigger)

What I have seen is that if I change the TargetType from **`"{x:Type iconPacks:PackIconModern}"`** to **`"iconPacks:PackIconModern"`** (_without {x:Type_), the designer works correctly.

I don't know if this is a real bug, and for the moment I have the workaround, but with the older version, this effect was not present.  

Thanks

**Comment by gigios** [comment]
The Visual Studio xaml editor marks many errors also if I open the PackIconModern.xaml resource dictionary file (MahApps.Metro.IconPacks\Themes folder).
I have tried also with the Bland editor and I have the same 'effect'.

**Comment by punker76** [comment]
It seems the main problem are the MarkupExtensions, cause the naming is the same as the normal Control. I will look at that.
