### ISSUE TITLE
iconPacks:PackIconSimpleIcons

### ISSUE THREAD

**Issue by ChGrand591** [MahApps/MahApps.Metro.IconPacks#291]
Hello

I am using wpf with powershell.

by example like this
https://github.com/damienvanrobaeys/MahApps_2.0_PS1_Theme_Manager

I have a program that works with an icon pack
for example
<iconPacks:PackIconOcticons Kind="Paintcan" Margin="0,5,0,0" ToolTip="Change the main theme of the tool"/>

but if I change to

  <iconPacks:PackIconSimpleIcons Kind="Symantec" /> this no longer works. 

thanks

**Comment by punker76** [comment]
It looks like there are a few dlls missing.

You need (if you use the main IconPacks NuGet):

- MahApps.Metro.IconPacks.dll
- MahApps.Metro.IconPacks.Core.dll
- MahApps.Metro.IconPacks.Octicons.dll (if you use Octicons)
- MahApps.Metro.IconPacks.SimpleIcons.dll (if you use SimpleIcons)
- and so on
