### ISSUE TITLE
Could not load file or assembly 'MahApps.Metro.IconPacks.FontAwesome, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0c0d510f9915137a' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by kunalguptaxd** [MahApps/MahApps.Metro.IconPacks#293]
Could not load file or assembly 'MahApps.Metro.IconPacks.FontAwesome, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0c0d510f9915137a' or one of its dependencies. The system cannot find the file specified.

**Comment by jizc** [comment]
This error should disappear as soon as you build your project after adding the NuGet package reference.

**Comment by Keiishu** [comment]
> This error should disappear as soon as you build your project after adding the NuGet package reference.

Worked for me. I added the solution in the wiki.
