### ISSUE TITLE
Publish icon file generators for use in PRs

### ISSUE THREAD

**Issue by jizc** [MahApps/MahApps.Metro.IconPacks#296]
### Is your feature request related to a problem? Please describe.
It's been 8 months since the last icon update was committed to this repo. In the case of Material Design icons, 400 icons has been added to the collection since then.

### Describe the solution you'd like
I would like the ability to generate the `PackIcon*DataFactory.cs` and `PackIcon*Kind.cs` files for existing icon packs. This would make it possible to contribute PRs that update the packages with the latest icons, reducing the workload of the maintainer.

### Describe alternatives you've considered
- I could manually update the files, but this would take a long time and go against `This code is auto generated. Do not amend.`
- I could make my own generator, but if one exists already, this seems like wasted time

### Additional context
I understand it can get tiresome to keep maintaining GitHub repositories. I would love to help ❤️ 

If the generators are available somewhere, and I just can't find them, please point me in the right direction 😄

**Comment by punker76** [comment]
@jizc Sorry for that. I will update the icons as soon as possible! I will not publish the converter, because the code is too hacky and some of the icons need hand actions to get it work. I hooe you understand that. 🤘

**Comment by jizc** [comment]
I understand 🙂 I ended up writing my own generator to make use of a more optimized fork of the Material icons collection.
