### ISSUE TITLE
VS2022 can't find IconPacks resource

### ISSUE THREAD

**Issue by dknippel** [MahApps/MahApps.Metro.IconPacks#307]
I've installed 4.11.0 via the NuGet Package Manager within VS2022.  However, when I run my app, it fails on `InitializeComponent()` and states:
>Could not load file or assembly 'MahApps.Metro.IconPacks.Modern blah blah blah'

At design time, the XAML designer appears to be able to find the resource like so: (see first screen scrape)

![XAML_desgin_time](https://user-images.githubusercontent.com/35277981/207402432-8678b67e-ec61-445d-940d-4839100198e3.png)

But when I run the app, it doesn't seem to find it like so: (see second screen scrape)

![XAML_parse_error](https://user-images.githubusercontent.com/35277981/207402439-f0668c2c-7119-4287-821a-82697a8db284.png)

Do I need to explicitly add a `ResourceDictionary` to my **_App.xaml_** perhaps like so:
```                <ResourceDictionary Source="Resources/graphics.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Light.Blue.xaml" />

                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro.IconPacks;component/Styles/Icons.xaml" />
```

When I try to add said `ResourceDictionary` it complains with:
>Cannot locate resource 'icons.xaml'

Everything worked great with the **_MahApps.Metro_** stuff, but not so much with the **_IconPacks_** stuff.  What am I missing?

**Comment by dknippel** [comment]
Hi @punker76 , is there anyway you could provide some help with this?

It appears to have several dependencies such as .NET Core 3.1, .NET 4.5, etc.  However, I only need it for .NET 4.7.2.  My IDE is VS2022, and my OS is Windows 11 Pro

Generally, the NuGet Manager seems to install dependencies correctly but I still seem to be missing something?  Am I missing something?  Again, what's weird is the IconPacks seems to work fine in design mode, but not runtime.

I've also tried to build from source via https://github.com/MahApps/MahApps.Metro.IconPacks/releases/tag/4.11.0 but that is another nightmare that appears to have even more dependencies.  Any advice you could provide would be great! :-)

**Comment by punker76** [comment]
@dknippel This sounds all very strange, because I never seen such errors.

**Comment by punker76** [comment]
@dknippel And it's not necessary to add any resource at App.xaml from IconPacks, except you want to override some styles.

**Comment by dknippel** [comment]
Hi @punker76 , thanks for your reply.  Yes, your WpfAppIconPacks2.zip sample works fine.  It is a bit different setup than mine.  Regardless, I am having to use the workaround described in UPDATE - PART DEUX above.  Still strange why none of the  **_MahApps.Metro.IconPacks_** assembly references get copied to the output directly.  Oh well :-|

**Comment by punker76** [comment]
@dknippel If it’s possible then send me your app, cause I’m interested in the different setup.

**Comment by dknippel** [comment]
I'm not sure if I can legally send you the app (government medical imaging technology).  However, it basically goes like this:

All .NET 4.7.2 components...

Host (console app)
 - DRACO Engine Manager (DLL)
   - this is where all the "models" of the `MVVM` approach exist
 - DRACO GUI (Windows Application)
   - this is where my WPF ("views" + "view models") stuff is and thus, where the MahApps stuff is
   - however, it does not use a `StartupUrl` in the `Appl.xaml`
   - rather, it spins up an `App` object and then calls `InitializeComponent()` which in turn loads in said `App.xaml`

So, life begins something like this:
1. The Host spins up an instance of the DRACO Engine Manager 
2. If that succeeds, the Host then spins up the DRACO GUI and passes in said engine manager
3. the engine manager and the GUI interact accordingly until the user terminates the application session

Obviously the DRACO GUI contains a reference to (via NuGet Manager):
 - MahApps.Metro
 - MahApps.Metro.IconPacks

And as one would expect in the Host output directory:
 - MahApps.Metro gets copied auto-magically due to the reference of DRACO GUI

However, what is not expected:
 - MahApps.Metro.IconPacks does NOT get copied auto-magically to the Host output directory.
 - A workaround is needed in which I have to explicitly add (via NuGet Manager) the MahApps.Metro.IconPacks package to Host

**Comment by kiranshahi** [comment]
Hi @dknippel have you solved this issue?

**Comment by dknippel** [comment]
Kind of I guess.  I mean, the workaround is:

> I have to explicitly add (via NuGet Manager) the MahApps.Metro.IconPacks package to Host
