### ISSUE TITLE
Update RemixIcon to V3.5

### ISSUE THREAD

**Issue by snowiceyeah** [MahApps/MahApps.Metro.IconPacks#310]

**Comment by snowiceyeah** [comment]
Is there a way to update version by myself? How to generate icondata(PackIconRadixIconsDataFactory.cs, PackIconRadixIconsDataFactory.cs)?

**Comment by punker76** [comment]
@snowiceyeah I am about to update the icons ;-)

![2024-04-23_23h18_36](https://github.com/MahApps/MahApps.Metro.IconPacks/assets/658431/6099c693-e2a6-4ca1-92c9-0f4ec76438a3)
