### ISSUE TITLE
IconPack spin not working

### ISSUE THREAD

**Issue by mydevel** [MahApps/MahApps.Metro.IconPacks#311]
Icon not spinning in runtime. The icon does spin in design time, but
not at runtime.

Example code:

`<iconPacks:Material
    Kind="GiftOutline" 
    Width="16" 
    Height="16"
    Spin="True"
    SpinDuration="3"/>`

MahApps.Metro.IconPacks 4.11.0
MahApps.Metro 2.3.10
.NET 7.0.402
Visual Studio 17.7.5
Windows 10

**Comment by punker76** [comment]
@mydevel I have no problem with it:

MahApps.Metro.IconPacks 4.11.0
MahApps.Metro 2.4.10
.NET 7.0
Visual Studio 17.8.3
Windows 10

[WpfApp1.zip](https://github.com/MahApps/MahApps.Metro.IconPacks/files/13678562/WpfApp1.zip)

https://github.com/MahApps/MahApps.Metro.IconPacks/assets/658431/25342cd2-64d4-4366-8d11-3bd1f4d94d50
