### ISSUE TITLE
Incompatibility: MahApps.Metro.IconPacks vs StrongNamer

### ISSUE THREAD

**Issue by Insire** [MahApps/MahApps.Metro.IconPacks#33]
Hi i have the following problem. I'd like to use [gong-wpf-dragdrop](https://github.com/punker76/gong-wpf-dragdrop) and i strongly signed my assembly with [StrongNamer](https://github.com/dsplaisted/strongnamer). But when starting my application, it cant find this library, which i installed via nuget.

When removing StrongNamer, IconPacks is found and loaded correctly. Is this a common issue? Is there a workaround?

Here is a [TestRepo](https://github.com/Insire/IconPacksSample/blob/master/IconPacksSample.7z) illustrating the issue.

[stacktrace.txt](https://github.com/MahApps/MahApps.Metro.IconPacks/files/730054/stacktrace.txt)

**Comment by Insire** [comment]
I found a workaround. I downloaded the Source of gong-wpf-dragdrop and signed it myself. Without using StrongNamer. Sadly i'll miss out on any updates you make to it. So I'm still looking for a solution for this problem.

**Comment by punker76** [comment]
@Insire Do you really need strongly signed app and assemblies?

**Comment by Insire** [comment]
I can't really say, because i don't know. This is for work related stuff and all the other assemblies we use are strongly signed. Do you think there is a solution? Or do I/we have to live with it as it is?

**Comment by punker76** [comment]
@Insire You can mix strongly named and non-strongly named dlls together if your app or dll doesn't need strongly signed. but if your app or dll needs to be strongly signed then all other referenced dlls must be strongly signed...

**Comment by Insire** [comment]
I figured as much. I thought strongnamer is supposed to "fix" that for me by strong naming assemblies who are not?

**Comment by Insire** [comment]
I kinda got an update on this Issue. StrongNamer still fails loading the signed IconPacks dll, but i can now use IconsPacks with your DragAndDrop library without signing either of them.

**Comment by Insire** [comment]
Oh right i used the most recent versions from nuget for this 

```
<package id="gong-wpf-dragdrop" version="1.1.0" targetFramework="net452" />
<package id="MahApps.Metro.IconPacks" version="1.9.0" targetFramework="net452" />
```

**Comment by punker76** [comment]
I will close this for now https://github.com/MahApps/MahApps.Metro.IconPacks/wiki/Usage#strong-naming
