### ISSUE TITLE
Merge all dlls into one

### ISSUE THREAD

**Issue by hupo376787** [MahApps/MahApps.Metro.IconPacks#341]
**Is your feature request related to a problem? Please describe.**
I installed MahApps.Metro.IconPacks, and I want them all. I don't want to install one by one.
But this leads to a problem, too many dlls in the exe folder.

So is there a dll that contains all icons? thx.

![image](https://github.com/MahApps/MahApps.Metro.IconPacks/assets/14960168/ed1c8fcc-66f5-427a-8849-5cf08400aa4e)

**Comment by SiriusED** [comment]
Same issue here, this is very bad approach to keep so many dlls

**Comment by punker76** [comment]
Can you guys give me a point why this is a bad approach? Thx

**Comment by hupo376787** [comment]
> Can you guys give me a point why this is a bad approach? Thx

I don't think this is bad. In our developer's view, this design is very good. You give many options to choose. 
But for some end developers and users, they may care too many files in their exe folder.

**Comment by batzen** [comment]
@hupo376787 Why would anyone care about the amount of files in the exe folder?
If they really care about the amount of files beside the exe they might consider publishing as a single file exe, when on .NET, or deploy with a private bin path and move all dependencies, or a subset, to a different folder, when on .NET framework.

**Comment by BirukTes** [comment]
This is not great in our case, we do not need all of the packs by making them dependency, you are forcing us to install them all and cannot uninstall them. The size of the app has significantly increased due this ~38 dependencies by about 45MB! We only had use for icons from Material pack and maybe few other packs.

I am not sure if making them Nuget dependencies is the correct approach because I am sure many other adaptors will have zero need for more than one or two packs. 

Please reconsider this approach.

**Comment by timunie** [comment]
@BirukTes I think updating the readme sounds reasonable. I think a PR would be welcome.

**Comment by BirukTes** [comment]
Hi @timunie, 

Updated the [Wiki ](https://github.com/MahApps/MahApps.Metro.IconPacks/wiki/Install)but it was my first time doing one of these, so I thought it was going to require review but it immediately saved everything. I would probably recommend to review it as soon as possible, in case you or anyone becomes unsatisfied, I am planning to update the table of contents links to below as well if you approve of the page changes... 

## Updated: Table of Contents
- [Install](https://github.com/MahApps/MahApps.Metro.IconPacks/wiki/Install)
- [Types of Installation](https://github.com/MahApps/MahApps.Metro.IconPacks/wiki/Install#types-of-installation)
  - [1. All-in-one: Install Every Icon Pack](https://github.com/MahApps/MahApps.Metro.IconPacks/wiki/Install#1-all-in-one-install-every-icon-pack)
  - [2. Selective: Install Only What You Need (Recommended)](https://github.com/MahApps/MahApps.Metro.IconPacks/wiki/Install#2-selective-install-only-what-you-need-recommended)
- [3. GUI Installation: Step-by-Step](https://github.com/MahApps/MahApps.Metro.IconPacks/wiki/Install#3-gui-installation-step-by-step)
- [4. Migrating from All-in-one to Selective Install](https://github.com/MahApps/MahApps.Metro.IconPacks/wiki/Install#4-migrating-from-all-in-one-to-selective-install)
- [Troubleshooting](https://github.com/MahApps/MahApps.Metro.IconPacks/wiki/Install#troubleshooting)
- [TL;DR](https://github.com/MahApps/MahApps.Metro.IconPacks/wiki/Install#tldr)

**Comment by timunie** [comment]
> but it immediately saved everything.

I didn't even know that this is possible, I thought that it would open a review PR. Since I am not the owner, I cannot finally judge. From my perspective your change make sense.
