### ISSUE TITLE
An exception was thrown while setting the property 'MahApps. Metro. InconPacks. PackIconMaterial. Kind

### ISSUE THREAD

**Issue by caradilin** [MahApps/MahApps.Metro.IconPacks#345]
**Describe the bug**

TypeLoadException: Could not load type 'MahApps.Metro.IconPacks.PackIconMaterialDataFactory' from assembly 'MahApps.Metro.IconPacks.Material, Version=5.0.0.0, Culture=neutral, PublicKeyToken=0c0d510f9915137a'.

Note: There is also a [gitter room](https://gitter.im/MahApps/MahApps.Metro.IconPacks) to ask about usage or something else.

**To Reproduce**
    xmlns:ext="http://schemas.abtsoftware.co.uk/scichart/exampleExternals"
Like：     <ext:ToolbarIcon Kind="CircleMultipleOutline"  Style="{StaticResource ToolbarButtonIconStyle}"/>
If I use IconPacks: PackIconMaterial, I also have the same problem.

**Screenshots**

<img width="486" alt="image" src="https://github.com/user-attachments/assets/e863f3a0-6bd3-4d5c-9d52-2986e380b698">

<img width="833" alt="image" src="https://github.com/user-attachments/assets/c53b8c75-5f35-4e9c-b8db-da4276455f16">

**Desktop Environment (please complete the following information):**
 - IconPacks Version: [e.g. v5.0.0]
 - Visual Studio: [e.g. 2022 17.10.x]
 - .NET Core: [e.g. 8.0]

**Repo**
If it's possible follow these guidelines for a good sample and I will most likely look at the issue sooner:

  - Post a full (small) GitHub repository. Not a zip file, half baked snippet etc. If GitHub is new to you consider it a great learning opportunity and chance to get involved.
  - The repository should have just ONE step max for me to get running, and that is "Restore NuGet Packages". If there are any other missing dependencies, or uncompiling features I will most likely move on to another issue.
  - I'm not trying to be awkward. I'm just busy and I'm helping a lot of people, not just you, so help me out and I will help you out.

**Additional context**

**Comment by timunie** [comment]
That's not a helpful ticket. Best to file a very minimal demo to investigate. I guess you have a package missmatch somewhere.

**Comment by caradilin** [comment]
Hey Tim, refer to ： https://github.com/caradilin/DemoTest/blob/main/WpfApp1/WpfApp1.sln

**Comment by timunie** [comment]
Sorry, but this is not a minimal demo. We have no time to investigate entire solutions.

**Comment by caradilin** [comment]
Sorry，updated completed.

**Comment by timunie** [comment]
Can't reproduce your issue. 🤷

**Comment by punker76** [comment]
@caradilin The problem is that the example NuGet package from SciChart has a dependency to MahApps.Metro.IconPacks v4.11.0

https://github.com/search?q=org%3AABTSoftware+MahApps.Metro.IconPacks.Material&type=code

So it's not possible to use v5.0 in you project.

**Comment by caradilin** [comment]
> @caradilin The problem is that the example NuGet package from SciChart has a dependency to MahApps.Metro.IconPacks v4.11.0
> 
> https://github.com/search?q=org%3AABTSoftware+MahApps.Metro.IconPacks.Material&type=code
> 
> So it's not possible to use v5.0 in you project.

Thx, Punker
