### ISSUE TITLE
MarkupExtension Namespace vs Name change

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro.IconPacks#38]
There is a problem with the current MarkupExtension naming and namespace. Visual Studio has problems with the properties of the MarkupExtension classes. The extensions doesn't have DependencyProperty implementations for the properties, but VS see this properties e.g. in a style and mark this usage with a warning.

>The property "Kind" is not a DependencyProperty. To be used in markup, non-attached properties must be exposed on the target type with an accessible instance property "Kind".

Here are the reported issues

- Designer error in a 'custom' style 'Setter' for an icon #29
- Designer and execution error due to "Flip" property #30

There are now 2 solutions to solve this issue (both are breaking changes)

1) 👍  Rename the extension `PackIconXYZ` -> `PackIconXYZExt`
```xaml
<Button Content="{iconPacks:PackIconMaterialExt AccessPoint}" />
```
2) 👎  Put the extension in a separated namespace
```xaml
   xmlns:ip="http://metro.mahapps.com/winfx/xaml/iconpacks"
   xmlns:ipExt="http://metro.mahapps.com/winfx/xaml/iconpacks/mextensions"
```
```xaml
<Grid>

    <StackPanel HorizontalAlignment="Center"
                VerticalAlignment="Center"
                Orientation="Vertical">
        <CheckBox IsChecked="True">
            <ip:PackIconModern>
                <ip:PackIconModern.Style>
                    <Style TargetType="{x:Type ip:PackIconModern}">
                        <Setter Property="Kind"
                                Value="Check" />
                        <Style.Triggers>
                            <DataTrigger Binding="{Binding IsChecked, RelativeSource={RelativeSource AncestorType=CheckBox}}"
                                         Value="False">
                                <Setter Property="Kind"
                                        Value="Close" />
                            </DataTrigger>
                        </Style.Triggers>
                    </Style>
                </ip:PackIconModern.Style>
            </ip:PackIconModern>
        </CheckBox>

        <Button Content="{ipExt:PackIconMaterial AccessPoint}" Margin="8" />

    </StackPanel>

</Grid>
```

I prefer first solution ;-)

**Comment by natiT** [comment]
Solution 1 seems to be more "Lightweight"!
