### ISSUE TITLE
Spin property still doesn't work during runtime

### ISSUE THREAD

**Issue by Elvaron** [MahApps/MahApps.Metro.IconPacks#45]
My ViewModel contains:
`public ObservableCollection<LogEntry> LogEntries { get; } = new ObservableCollection<LogEntry>();`

with a UserControl for log entries:
[UserControl.xaml.txt](https://github.com/MahApps/MahApps.Metro.IconPacks/files/949774/UserControl.xaml.txt)

which is added to a MetroWindow via a _TransitioningContentControl_.

Everything works - Text binding, icon binding, color binding - as far as the icons themselves are concerned, but they don't spin. Even if I change the binding to a static value of in the .xaml like ` Spin="True" `.

LogEntry class for reference, just in case, but it shouldn't make any difference:
[LogEntry.cs.txt](https://github.com/MahApps/MahApps.Metro.IconPacks/files/949776/LogEntry.cs.txt)

**Comment by punker76** [comment]
@Elvaron Which version do you use?

**Comment by punker76** [comment]
@Elvaron Can you create a working sample app on GitHub? Thx.

**Comment by Elvaron** [comment]
Sorry for the delay, I'll supply an example in a few minutes.
Version is 1.9.0

**Comment by Elvaron** [comment]
Example project:
https://github.com/Elvaron/MahApps.Metro.IconPacks.IssueExample

Sorry about it being a bit more than strictly necessary, but extracting from existing code this way was easier than writing something from scratch.
In this case it's a command line application, my actual project is a VSIX Project, so the MetroWindow gets created from a context-menu entry click in Visual Studio.

Steps to reproduce: Clone, build, run, hit OK button. It creates a new log entry with 2 icons, one having static `Spin="True"` in the XAML, the other using `Spin="{Binding Path=Spin}"`

**Comment by punker76** [comment]
@Elvaron I'll publish this with 1.9.1

**Comment by Elvaron** [comment]
Awesome! Thanks a lot for the fast response, and a great set of plugins!
