### ISSUE TITLE
Binding to icon type and kind, from string

### ISSUE THREAD

**Issue by FolkCoder** [MahApps/MahApps.Metro.IconPacks#46]
I have an application that currently uses the loose xaml icon file from MahApps.Metro.Resources. The application retrieves a large collection of objects from a database, including a string representing the resource key of the icon (for example, appbar_lock). I then use a converter (using TryFindResource) to convert the string to a matching resource key.

This setup works fairly well for me, and I'm able to store the object's icon with all of the other metadata in the database. However, I'd like to move to the newer IconPacks in order to take advantage of the continuing support and additional icons.

Is there a way to accomplish this setup within IconPacks?

**Comment by punker76** [comment]
@FolkCoder Yes you can do something similar when you take one of the enumerations of the IconPack kinds. The browser does this for example

https://github.com/MahApps/MahApps.Metro.IconPacks/blob/82eb00457bc0e93fe09f623d28a094e66411fa46/src/MahApps.Metro.IconPacks.Browser/ViewModels/IconPackViewModel.cs#L57-L82

**Comment by mythjuha** [comment]
The example could use a bit more explanation. How to go from a string (preferably representing any icon pack) to an iconpack control?
