### ISSUE TITLE
Add signed version of the assembly

### ISSUE THREAD

**Issue by maggarwal** [MahApps/MahApps.Metro.IconPacks#49]
Hi,

I wanted to use this library in my application but can't because my application is requires strong named assemblies. All other MahApps packages are signed, can you please add this one as well?

Thanks

**Comment by Insire** [comment]
[StrongNamer](https://github.com/dsplaisted/strongnamer) can help you out there.

**Comment by punker76** [comment]
I will not do this https://github.com/MahApps/MahApps.Metro.IconPacks/wiki/Usage#strong-naming

**Comment by maggarwal** [comment]
@Insire  That's not really a solution. This is a open repository and you guys are asking me to maintain a separate copy of it just so that I can use it in my code. Signing isn't something only one person needs and doesn't really add any overhead to the developement and should be added. Also since the parent MahApps library is signed then I don't see any reason why this can't be. It forces people to dump these libraries and try to find alternatives or just not use something like this to start with. Such a shame that you guys are just telling people to piss off.

**Comment by punker76** [comment]
@maggarwal Sorry about feeling pissed off! That was not my intention.

MahApps.Metro.IconPacks will not be strong-named.

Why?

Strong-named assemblies are only useful in some rare scenarios. And yes, if you need strong-named assembly then you can compile the source by yourself (if the following shown tools doesn't work) ore use the [Strong Namer](https://github.com/dsplaisted/strongnamer) from Daniel Plaisted @dsplaisted or [Strong-Name Signer](https://github.com/brutaldev/StrongNameSigner) from Werner van Deventer @brutaldev.

More Informations about the reason of this change can be found here:

- [Still Strong-Naming your Assemblies? You do know it’s 2016, right?](https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/)
- [XAML Behaviors UWP Managed 1.1.0](https://www.pedrolamas.com/2016/02/23/xaml-behaviors-uwp-managed-1-1-0/)
- [Strong-Named Assemblies](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies)
