### ISSUE TITLE
How do I get the demo app in the GIF in ReadMe.md?

### ISSUE THREAD

**Issue by CADbloke** [MahApps/MahApps.Metro.IconPacks#5]
Greetings.

Apologies upfront for the noobness of this: I tried the MahApps demo app. I found the [click code-behind for the "Icons" link in the title bar and where it changed](https://github.com/MahApps/MahApps.Metro/commit/477684bd4a3c487d215662518128389e81a62c36#diff-40d1cda2b138001c28772f133a103162)  but all it does now is link to this repo, which is nice but it's not that app. 

Reason is, it's a nice easy way to find icons. Or am I thinking it wrong? Is there a better way to choose teh icons?

cheers & thanks for all the MahApps
Ewen

**Comment by punker76** [comment]
@CADbloke Hi, I'm currently working on a new demo application where you can search.and copy and maybe some more...

**Comment by CADbloke** [comment]
Awesome. I'll keep an eye out. I'd offer to help but I think I'd just slow you down. Call on me if you need some weeping or to feed the cat. :)
