### ISSUE TITLE
After Install Package not running

### ISSUE THREAD

**Issue by evan-boissonnot** [MahApps/MahApps.Metro.IconPacks#53]
Hi everyone

I'm trying to use your package.

I launch the Install-Package MahApps.Metro.IconPacks on my wpf projet in vs 2017 community.

After that, I'm starting to use th icon pack.

1. I add xmlns : xmlns:iconPacks="http://metro.mahapps.com/winfx/xaml/iconpacks"

2. I try this <iconPacks:PackIconMaterial Kind="EmoticonCool" VerticalAlignment="Center" HorizontalAlignment="Center" />

But PackIconMaterial is not recognized.

Whats is happening ?

**Comment by punker76** [comment]
@evan-boissonnot Is it not running? Is your project in GitHub?

**Comment by evan-boissonnot** [comment]
Hi Punker76, 

Nop, but I'll create you tomorow a project to show. It wil be better I think, nop ? :)

**Comment by schdck** [comment]
Any news @evan-boissonnot?

**Comment by evan-boissonnot** [comment]
Hi

Everything is ok, now ...
Apologize to forget you :D I have a lot to do with my project.

After update my VS everything is ok :)

Not understand what was going on ..

See you.


Bien cordialement
__________________________________________
Evan BOISSONNOT - Entrepreneur agile
Site : http://evanboissonnot.fr

Vous entreprenez pour de vrai ?
<http://entreprendrepourdevrai.fr/tous-mes-articles/>

Tel. : 06 10 37 52 10

*Je pratique l'écologie temporelle : je ne regarde mes mails qu'à 12h30
tous les jours (sauf le week-end). Je vous réponds donc au maximum dans une
journée.*

2017-09-18 18:22 GMT+02:00 Maurício Vielmo Schmaedeck <
notifications@github.com>:

**Comment by evan-boissonnot** [comment]
Bonjour,

Peut-être avez-vous déjà voté pour le projet *La diagonale du poulpe*,
alors un grand MERCI!

Si ce n'est pas le cas et que vous souhaitez aider *La diagonale du poulpe*
, alors soutenez-le en votant pour *son projet* !

Pour vous c'est moins de deux minutes, pour *La diagonale du poulpe* c'est
peut-être la chance de pouvoir décrocher un soutien financier de *2000 à
15000*€ ! C'est loin d'être négligeable.

Le vote se fait jusqu'au *10 avril* sur internet, c'est gratuit et sans
engagement.

Il suffit d'aller sur le lien suivant :
https://lafabrique-france.aviva.com/voting/projet/vue/30-1583 .

 Ensuite, il faut S'INSCRIRE, puis vous recevez un e-mail de confirmation
qui vous permet de voter.

Vous disposez de 10 votes et pouvez offrir vos 10 votes au même projet.
N'hésitez pas à diffuser ce lien, à encourager votre entourage à voter.

Et rappelez-vous :
1 ADRESSE MAIL = 10 VOTES
SI ON A PLUSIEURS ADRESSES MAIL, ON PEUT VOTER PLUSIEURS FOIS !

Si vous rencontrez des difficultés pour voter (ce qui semble arriver de
temps en temps), n'hésitez pas à m'en faire part, je vous aiderai !

Merci et à bientôt !
__________________________________________
Evan BOISSONNOT - Entrepreneur agile
Site : http://evanboissonnot.fr

Tel. : 06 10 37 52 10


*Je pratique l'écologie temporelle : je ne regarde mes mails qu'à 12h00
tous les jours (sauf le week-end). Je vous réponds donc au maximum dans une
journée.Si très important, appelez-moi :)*
