### ISSUE TITLE
Icon binds only to first datagrid row

### ISSUE THREAD

**Issue by thombrink** [MahApps/MahApps.Metro.IconPacks#56]
If I add an icon to a button in a datagrid in WPF everything works just fine.
But when I try to use it inside a DataTrigger, only the first row of my datagrid shows an image.

```
<Button>
    <Button.Style>
        <Style TargetType="Button">
            <Style.Triggers>
                <DataTrigger Binding="{Binding Order_Status.In_Prima}" Value="true">
                    <Setter Property="Content" Value="{iconPacks:PackIconFontAwesome StarOutline}" />
                </DataTrigger>
                <DataTrigger Binding="{Binding Order_Status.In_Prima}" Value="false">
                    <Setter Property="Content" Value="{iconPacks:PackIconFontAwesome StarOutline}" />
                </DataTrigger>
            </Style.Triggers>
        </Style>
    </Button.Style>
<Button>
```

**Comment by JazzmanMarburg** [comment]
Hi, did you solve this issue anyhow?
I have a similar problem when I try to bind an Icon several times: Only the last icon will be shown - the "old" icons disappear. Would be interesting to see your solution - if you have one.
Regards

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro.IconPacks/releases).

Thank you! 🙏

**Comment by timunie** [comment]
Hello together,

just in case someone is still interested in a solution: 
The problem is, that in WPF the `Content` property can only set once, if it is a `Visual`. But luckily you can set the `ContentTemplate` to a `DataTemplate` and then the `Style` should work as expected. 

```xaml 
<Button>
    <Button.Style>
        <Style TargetType="Button">
            <Style.Triggers>
                <DataTrigger Binding="{Binding Order_Status.In_Prima}" Value="true">
                    <Setter Property="ContentTemplate">
                        <Setter.Value>
                               [YOUR DATATEMPLATE GOES HERE]
                        </Setter.Value>
                    </Setter>
                </DataTrigger>
                <DataTrigger Binding="{Binding Order_Status.In_Prima}" Value="false">
                    <Setter Property="Content">
                        <Setter Property="ContentTemplate">
                            <Setter.Value>
                                   [YOUR DATATEMPLATE GOES HERE]
                            </Setter.Value>
                        </Setter>
                </DataTrigger>
            </Style.Triggers>
        </Style>
    </Button.Style>
<Button>
 ```

Happy coding
Tim
