### ISSUE TITLE
Font Awesome 5.0 naming

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro.IconPacks#61]
The new [Font Awesome 5.0](https://fontawesome.com/) introduce new sub groups `Regular`, `Solid` and `Brands`, so I want to know which is the best name for the enumeration. 

1) 
```
far_FontAwesomeName
fas_FontAwesomeName
fab_FontAwesomeName
```
2)
```
FontAwesomeNameRegular
FontAwesomeNameSolid
FontAwesomeNameBrands
```
3)
```
RegularFontAwesomeName
SolidFontAwesomeName
BrandsFontAwesomeName
```

**Comment by amkuchta** [comment]
I vote for the first choice, as it sticks to the FA5 pro naming convention (kind of)

**Comment by punker76** [comment]
My vote goes to the second one, cause the old names had some similar naming like `FontAwesomeNameOutline`

**Comment by amkuchta** [comment]
@punker76 I feel like sometimes, you just want to disagree with me 😆 😆 😆

**Comment by punker76** [comment]
@amkuchta sorry, It's nothing with you...
