### ISSUE TITLE
Possible new [IconSet] - Feather

### ISSUE THREAD

**Issue by Insire** [MahApps/MahApps.Metro.IconPacks#67]
Just stumbled across this [project](https://github.com/feathericons/feather#feather) and thought that it might be a good addition to the icon pack. Preview can be found [here](https://feathericons.com/). Its licensed under MIT.

**Comment by Phyxion** [comment]
Yes, this would be a nice addition indeed. ModernUI icon pack is deprecated so perhaps it would make sense to remove that one and use this instead.

**Comment by punker76** [comment]
First try is coming (but not for PathIcon, because it's not working for this control)

![2018-10-19_08h57_46](https://user-images.githubusercontent.com/658431/47202540-c4bea000-d37d-11e8-81e3-af31ba3116dd.png)

**Comment by punker76** [comment]
Added in e1cbf5b423217e7dec2195b6a581b32a805cb516
