### ISSUE TITLE
[WPF] PackIconMaterial on property Glyph

### ISSUE THREAD

**Issue by FabricioBonifacio** [MahApps/MahApps.Metro.IconPacks#69]
Hi,

I'm trying to use a icon from PackIconMaterial inside a property Glyph from element AppButtonBar (DevExpress) and i'm getting below error:

_MahApps.Metro.IconPacks.PackIconMaterial' is not a valid value to 'Glyph' property._

My Code:

_<dxwui:AppBarButton Label="Refresh" HorizontalAlignment="Center" IsEllipseEnabled="False" Glyph="{iconPacks:PackIcon {x:Static iconPacks:PackIconMaterialKind.Loop}, Width=32, Height=32}" />_

There's some way to use the icons inside a Glyph?

Thanks in advance.

**Comment by punker76** [comment]
@FabricioBonifacio Question is: What which type is that `Glyph` property?

**Comment by FabricioBonifacio** [comment]
It is an ImageSource.

**Comment by punker76** [comment]
@FabricioBonifacio Ok, that's the problem, cause the `PackIconXYZ` are inherited from `Control`  and not `ImageSource`. There is already an issue here for this https://github.com/MahApps/MahApps.Metro.IconPacks/issues/39 so maybe you can use this workaround until it's official in here.

**Comment by FabricioBonifacio** [comment]
@punker76 OK. Thanks.
