### ISSUE TITLE
Controlling size from container

### ISSUE THREAD

**Issue by barishamil** [MahApps/MahApps.Metro.IconPacks#70]
Width and Height given in default style prevents making the icon take the size of its container

**Comment by punker76** [comment]
@barishamil You can override this with `Width="Auto"` and `Height="Auto"` on the PackIconXYZ

**Comment by barishamil** [comment]
@punker76 I didn't want to override default styles or assign a style for each icon because I already assigned styles for the containers but this will have to do

**Comment by barishamil** [comment]
Auto by itself makes it 1600x1600, is there a way to make auto size take 1x1 so I can set Min(Width|Height)?
