### ISSUE TITLE
Update Control Name to Match MarkupExtension

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro.IconPacks#71]
Currently, if I use an Icon as its own control, I have to use the following syntax:

```xaml
<IconPacks:PackIconFontAwesome Kind="BookmarkRegular" />
```

If I use the icon as a `MarkupExtension`, the syntax is slightly different (specifically, `PackIconFontAwesome` becomes a simple `FontAwesome`, which I think is perfect):

```xaml
<Button Content="{iconPacks:FontAwesome Kind=BookmarkRegular}" />
```

Can the control syntax be updated to match the `MarkupExtension` syntax for consistency?  Example:

```xaml
<IconPacks:FontAwesome Kind="BookmarkRegular" />
```

**Comment by punker76** [comment]
@amkuchta I must say no, cause then I have the same problem as before that the VS designer doesn't works correct with custom styles or mixing usage of the MarkupExtensions and the controls.

**Comment by amkuchta** [comment]
Ah, I see.  Ok, I'll close - thanks for the response!
