### ISSUE TITLE
Error: 'Flip' property was already registered by 'MahApps_Metro_IconPacks_PackIconControl`1_13_147733582'

### ISSUE THREAD

**Issue by SaadTiwana** [MahApps/MahApps.Metro.IconPacks#79]
Hi, 
I get the following error every time i use any icons from MahApps.Metro.IconPacks in my WPF project in VS2017:

Error: 'Flip' property was already registered by 'MahApps_Metro_IconPacks_PackIconControl`1_13_147733582'

Packages i have installed in the project include:
MahApps.Metro
MahApps.Metro.IconPacks
ControlzEx (Installed as a dependency automatically, i don't manually install it)

All the installations were done using NuGet Package manager in VS2017.

Pls note that, due to the above error, the XAML  visualizer doesn't show the Icons at design time, but at run time the icons appear correctly. The way i am using the Icons in my buttons is the following:

<Button x:Name="Btn_ZoomFitContents"  HorizontalAlignment="Right" Height="70" Margin="0, 0,2,30" VerticalAlignment="Bottom" Width="70" Click="Btn_ZoomFitContents_Click">
                    <iconPacks:PackIconMaterial Kind="FullScreen" Height=" auto" Width="auto" Padding="2"/>
</Button>

I have tried several things but am unable to find a solution; Google search didn't bring any results either. Hoping to get a resolution on this. Thank you.

**Comment by punker76** [comment]
@SaadTiwana Can you additionally add the versions for the installed NuGet libs? Is this app on GitHub?

**Comment by SaadTiwana** [comment]
@punker76 Thank you for the quick response.

The versions are the latest as of this moment, details below:
MahApps.Metro v1.6.2
MahApps.Metro.IconPacks v2.2.0
ControlzEx v3.0.2.4

The app is not on github unfortunately. Please let me know if any other information is required.

**Comment by punker76** [comment]
@SaadTiwana What is the selected Platform (Any CPU, x86, x64)? Which VS 2017 version?

**Comment by SaadTiwana** [comment]
@punker76 
The Platform is x64 (i cannot use x86 due to some other binaries being used), and i'm using vs2017 Community edition.
Targer framework is .Net 4.7.1

**Comment by punker76** [comment]
@SaadTiwana So, yeah, that's the problem, the VS designer has view problems with x64 compiled assemblies / apps, cause the designer itself is x86. This problem exists a very long time and I can not say when this will be fixed by the VS team.

**Comment by SaadTiwana** [comment]
@punker76 Thank you for pointing that out. I at-least now see that the controls appear fine in x86 mode. 
My workaround is that i can switch to x86 just during design time to see the changes in the designer, and then switch to x64 when compiling. Thanks a lot for pointing this out to me. I will now close this issue.

p.s Your Icon packs are awesome!! I am in love with them, and the MahApps.Metro ecosystem. Thank you for making them available to all of us :)
