### ISSUE TITLE
can use IconPacks on Window control

### ISSUE THREAD

**Issue by Motorcure** [MahApps/MahApps.Metro.IconPacks#80]
<Window x:Class="MahAppsMetroTest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:local="clr-namespace:MahAppsMetroTest"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        Title="MainWindow"
        Icon="1.ico"
        Width="525"
        Height="350"
        mc:Ignorable="d">

if i need use some icon in the IconPacks, how can i used like this

Icon="<materialDesign:PackIcon Kind="SomeMaterialIcon" />"

**Comment by punker76** [comment]
@Motorcure You can not use it for the Icon property of the Window, cause it needs an `ImageSource`. If you use MahApps.Metro then you can use the `IconTemplate` property to set what you want as an icon.

**Comment by Motorcure** [comment]
can use IconTemplate with IconPacks for the Icon property of the Window?
