### ISSUE TITLE
Iconpacks precompiled browser (.exe) triggers antivirus

### ISSUE THREAD

**Issue by erotavlas** [MahApps/MahApps.Metro.IconPacks#84]
Symantec anti virus has quarantined (deleted) the icon packs browser executable from my computer.

Threat: Heur.AdvML.B

File: IconPacks.Browser.v2.2.0.zip>>MahApps.Metro.IconPacks.Browser.exe

Action taken: Cleaned by Deletion

**Comment by punker76** [comment]
@erotavlas Maybe this is caused by not signing the executable. If I scan it with my ESET then I got no virus detection.
