### ISSUE TITLE
"Margin" and "Foreground" properties for Octicons & FontAwesome

### ISSUE THREAD

**Issue by jean309** [MahApps/MahApps.Metro.IconPacks#86]
After a update from version 1.9* to 2.2.0 :
"Margin" and "Foreground" properties are not found for "Octicons" & "FontAwesome"
But they still still exist for "PackIconMaterial" 
Sample :  
```
 <MenuItem.Icon>
<iconPacks:Octicons Kind="Sync" Margin="5 0 0 0" Foreground="{DynamicResource xxxx}"/>
 </MenuItem.Icon> 
```

**Comment by punker76** [comment]
@jean309 You are using the MarkupExtension class instead the PackIcon class. So if you use the correct class then it should work https://github.com/MahApps/MahApps.Metro.IconPacks#wpf-sample

```xaml
<MenuItem.Icon>
  <iconPacks:PackIconOcticons Kind="Sync" Margin="5 0 0 0" Foreground="{DynamicResource xxxx}" />
</MenuItem.Icon>
```
