### ISSUE TITLE
using icons in NavigationView of UWP

### ISSUE THREAD

**Issue by touseefbsb** [MahApps/MahApps.Metro.IconPacks#98]
I was trying to use some icons in the **NavigationView** of my uwp app but as it turns out **NavigationViewItem.Icon** only accepts following types.
1. SymbolIcon
2. BitmapIcon
3. FontIcon

and since IconPacks is not any of those how can they be used in this scenario?

**Comment by punker76** [comment]
@touseefbsb That's a weird restriction to base class IconElement. I'll look for a solution.

**Comment by touseefbsb** [comment]
I agree it is a very weird restriction. it should allow any kind of content instead of limiting to an IconElement only

**Comment by punker76** [comment]
@touseefbsb Working in it...

**Comment by touseefbsb** [comment]
@punker76  Thanks, I guess you are are changing the icon to produce fontIcon instead of normal Icon as content? While making the change please make sure that the icons can change its color and can respond to uwp theme toggle.

**Comment by punker76** [comment]
@touseefbsb https://github.com/MahApps/MahApps.Metro.IconPacks/pull/99

**Comment by touseefbsb** [comment]
yeah the fix looks great. Thanks.

**Comment by touseefbsb** [comment]
@punker76  I checked the pre-release package on nuget is still not updated to the dev branch.

**Comment by punker76** [comment]
@touseefbsb 3.0.0-alpha0065 should be available now on NuGet

**Comment by touseefbsb** [comment]
currently its 0061, I think it might take some time to appear in the search.
